import { describe, expect, it } from "vitest";

import parity from "./data/wp-html-escape-url-parity.json";
import tables from "./data/html5-entities.json";
import { escapeUrl, unescape } from "./escape-url";

/**
 * `mistune.util.escape_url` and the `unescape` it composes, replayed against
 * the real Python functions. `parity.cases` is generated by
 * `api/scripts/export_wp_html_escape_url_parity.py`; every expectation in the
 * replay block came out of Python, not out of this file.
 *
 * The hand-written blocks below are controls, not a second oracle: each one
 * pins a branch whose absence a smaller corpus would not notice.
 */

type Case = {
  name: string;
  input: string;
  unescaped: string;
  escaped: string;
};
type Raises = {
  name: string;
  input: string;
  raises: string;
  message: string;
};

const cases = parity.cases as Case[];
const raises = parity.raises as Raises[];

describe("escapeUrl", () => {
  it("has an oracle generated from the Python implementation", () => {
    expect(parity.source).toBe(
      "mistune.util.escape_url and mistune.util.unescape",
    );
    expect(parity.safe_set).toBe(":/?#@!$&()*+,;=%");
    expect(cases.length).toBeGreaterThanOrEqual(85);
  });

  it("carries the three stdlib tables verbatim", () => {
    expect(Object.keys(tables.html5)).toHaveLength(2231);
    expect(Object.keys(tables.invalid_charrefs)).toHaveLength(34);
    expect(tables.invalid_codepoints).toHaveLength(126);
  });

  describe("matches the Python output", () => {
    for (const c of cases) {
      it(c.name, () => {
        expect(unescape(c.input)).toBe(c.unescaped);
        expect(escapeUrl(c.input)).toBe(c.escaped);
      });
    }
  });
});

describe("escapeUrl deviations", () => {
  // Python encodes with errors='strict', so `str.encode('utf-8')` raises on an
  // unpaired surrogate and the converter crashes. `TextEncoder` substitutes
  // U+FFFD instead, so this port returns the encoding of the replacement
  // character. The oracle records what Python did.
  it("substitutes U+FFFD where Python raised UnicodeEncodeError", () => {
    expect(raises).toHaveLength(2);
    for (const r of raises) {
      expect(r.raises).toBe("UnicodeEncodeError");
      expect(escapeUrl(r.input)).toBe("%EF%BF%BD");
    }
  });
});

describe("unescape branches the corpus alone would not pin", () => {
  // `_replace_charref` looks a name up by identity. A port that used `in` on
  // the imported JSON object would resolve every Object.prototype key, and
  // `String(HTML5.constructor)` would land in the URL.
  it("does not resolve Object.prototype keys as entity names", () => {
    for (const key of [
      "constructor",
      "toString",
      "valueOf",
      "hasOwnProperty",
      "__proto__",
      "isPrototypeOf",
    ]) {
      expect(unescape(`&${key};`)).toBe(`&${key};`);
    }
  });

  // `&lt;` resolves as an exact name; `&ltx;` resolves through the
  // longest-prefix loop, which is the only path that reaches a name with no
  // semicolon spelling. The loop's `range(len(s) - 1, 1, -1)` lower bound is
  // unobservable: `html5` has no one-character name, so nothing can resolve
  // there whether the loop stops at 2 or at 1.
  it("resolves a name through the longest-prefix loop", () => {
    expect(unescape("&ltx;")).toBe("<x;");
    expect(unescape("&lx;")).toBe("&lx;");
  });

  // The pattern requires the semicolon, which the stdlib's does not.
  it("requires the trailing semicolon", () => {
    expect(unescape("&amp")).toBe("&amp");
    expect(unescape("&amp;")).toBe("&");
  });

  // `int()` accepts leading zeros, and the hex form has no digit bound while
  // the decimal form is capped at seven digits by the pattern.
  it("accepts leading zeros in a hex reference but bounds the decimal digits", () => {
    expect(unescape("&#x00000000026;")).toBe("&");
    expect(unescape("&#0000037;")).toBe("%");
    expect(unescape("&#00000037;")).toBe("&#00000037;");
  });

  // A hex reference has no digit bound, so the value can be larger than a JS
  // number holds exactly. It only has to compare greater than U+10FFFF.
  it("treats an absurdly long hex reference as above the Unicode maximum", () => {
    expect(unescape(`&#x${"f".repeat(40)};`)).toBe("�");
    // U+10FFFF is itself a noncharacter, so the highest codepoint that
    // survives the tables is one below it.
    expect(unescape("&#x10FFFD;")).toBe(String.fromCodePoint(0x10fffd));
  });

  // The three tables are consulted in this order: a remapped charref wins over
  // the surrogate check, which wins over the dropped codepoints.
  it("consults the three tables in Python's order", () => {
    // 0x0D is in _invalid_charrefs and would otherwise be a bare control char.
    expect(unescape("&#13;")).toBe("\r");
    // 0x01 and 0x0B are in _invalid_codepoints and resolve to nothing.
    expect(unescape("&#1;")).toBe("");
    expect(unescape("&#11;")).toBe("");
    // 0x09 is a control character in neither table and survives.
    expect(unescape("&#9;")).toBe("\t");
  });

  it("takes the fast path only when there is no ampersand", () => {
    expect(unescape("no references here")).toBe("no references here");
  });
});

describe("quote branches the corpus alone would not pin", () => {
  // The encoding is of UTF-8 bytes, not of characters. A port that percent
  // encoded `charCodeAt` values would emit `%E9` for a latin-1 character
  // rather than `%C3%A9`.
  it("percent encodes UTF-8 bytes, not code units", () => {
    expect(escapeUrl("é")).toBe("%C3%A9");
    expect(escapeUrl("\u{1F600}")).toBe("%F0%9F%98%80");
  });

  it("emits upper-case hex", () => {
    expect(escapeUrl("<")).toBe("%3C");
    expect(escapeUrl("\u007F")).toBe("%7F");
  });

  // `%` is in the safe set precisely so an already-encoded octet survives.
  it("does not double encode an existing percent escape", () => {
    expect(escapeUrl("https://example.com/a%20b")).toBe(
      "https://example.com/a%20b",
    );
  });

  // `'` and `[`/`]` are deliberately left out of the safe set.
  it("encodes the sub-delims and gen-delims the safe set omits", () => {
    expect(escapeUrl("'")).toBe("%27");
    expect(escapeUrl("[")).toBe("%5B");
    expect(escapeUrl("]")).toBe("%5D");
  });
});
