/**
 * `mistune.util.escape_url`, ported to TypeScript. Ledger item
 * 5.3c-iii-b-1-b-ii-3-b-1.
 *
 * ```python
 * def escape_url(link: str) -> str:
 *     safe = ":/?#@!$&()*+,;=%"
 *     return quote(unescape(link), safe=safe)
 * ```
 *
 * Two lines, and neither of the things they call exists in JavaScript.
 *
 * `unescape` is `html.unescape` with a CommonMark-flavoured pattern: an entity
 * reference must carry its trailing semicolon to be recognised, so `&amp` stays
 * literal where the stdlib would resolve it. Everything past the pattern is the
 * stdlib's `_replace_charref`, which needs three of its tables:
 * `html.entities.html5` (2231 names, both the `;` and the bare spellings),
 * `html._invalid_charrefs` (the Windows-1252 remapping plus `&#0;` and `&#13;`)
 * and `html._invalid_codepoints` (which resolve to nothing at all). Those are
 * data, so `data/html5-entities.json` holds them exported verbatim rather than
 * retyped.
 *
 * `quote` is `urllib.parse.quote`, which percent encodes the *UTF-8 bytes* of
 * every character outside `A-Za-z0-9_.-~` plus the caller's safe set, with
 * upper-case hex. Byte-wise, not character-wise: `é` is two bytes and becomes
 * `%C3%A9`.
 *
 * The interesting behaviour is at the seam. `&amp;` unescapes to `&`, which is
 * in the safe set and survives as a literal `&`; `&lt;` unescapes to `<`, which
 * is not, and becomes `%3C`. And because `%` is safe, an already-encoded octet
 * is left alone rather than double encoded, which is the entire reason `%` is
 * in that set.
 *
 * `data/wp-html-escape-url-parity.json` is the oracle, generated by
 * `api/scripts/export_wp_html_escape_url_parity.py` from the real function.
 *
 * Deviation: Python encodes with `errors='strict'`, so a lone surrogate raises
 * `UnicodeEncodeError` and crashes the converter. `TextEncoder` has no strict
 * mode and substitutes U+FFFD, so this port returns `%EF%BF%BD` where Python
 * raised. That removes an error path rather than adding one, and a lone
 * surrogate cannot survive the JSON transport the markdown arrives over anyway.
 * The two inputs are pinned in the oracle's `raises` array.
 */

import tables from "./data/html5-entities.json";

/**
 * `html.entities.html5`. A `Map`, not the imported object: the names come from
 * user text, and `"constructor" in obj` is true on a plain object, which would
 * resolve `&constructor;` to a function.
 */
const HTML5 = new Map<string, string>(Object.entries(tables.html5));

/** `html._invalid_charrefs`: mostly the Windows-1252 remapping of 0x80-0x9F. */
const INVALID_CHARREFS = new Map<number, string>(
  Object.entries(tables.invalid_charrefs).map(([code, char]) => [
    Number(code),
    char,
  ]),
);

/** `html._invalid_codepoints`, which `_replace_charref` maps to the empty string. */
const INVALID_CODEPOINTS = new Set<number>(tables.invalid_codepoints);

/**
 * `mistune.util._charref_re`. The stdlib's pattern allows a name with no
 * trailing `;`; this one does not, which is the CommonMark rule.
 */
const CHARREF_RE = /&(#[0-9]{1,7};|#[xX][0-9a-fA-F]+;|[^\t\n\f <&#;]{1,32};)/g;

/** Python `str.rstrip(";")`: every trailing semicolon, not just one. */
function rstripSemicolons(s: string): string {
  let end = s.length;
  while (end > 0 && s[end - 1] === ";") end -= 1;
  return s.slice(0, end);
}

/** `html._replace_charref`, applied to the pattern's group 1. */
function replaceCharref(ref: string): string {
  if (ref[0] !== "#") {
    // A named reference. The exact name wins; failing that the standard says
    // to take the longest prefix that is a name, which is how `&notit;` turns
    // into `¬it;`. The loop stops at 2, so a one-character prefix never wins.
    const exact = HTML5.get(ref);
    if (exact !== undefined) return exact;
    for (let x = ref.length - 1; x > 1; x -= 1) {
      const prefix = HTML5.get(ref.slice(0, x));
      if (prefix !== undefined) return prefix + ref.slice(x);
    }
    return `&${ref}`;
  }

  let num: number;
  if (ref[1] === "x" || ref[1] === "X") {
    // The hex form has no digit bound, where Python's `int` is arbitrary
    // precision and `parseInt` is not. It does not matter: a value that needs
    // more than 13 hex digits is far above the Unicode maximum, and rounding
    // (or `Infinity`) still compares greater, which is all the checks below ask.
    num = parseInt(rstripSemicolons(ref.slice(2)), 16);
  } else {
    num = Number(rstripSemicolons(ref.slice(1)));
  }

  const invalid = INVALID_CHARREFS.get(num);
  if (invalid !== undefined) return invalid;
  if ((num >= 0xd800 && num <= 0xdfff) || num > 0x10ffff) return "�";
  if (INVALID_CODEPOINTS.has(num)) return "";
  return String.fromCodePoint(num);
}

/** `mistune.util.unescape`. */
export function unescape(s: string): string {
  if (!s.includes("&")) return s;
  return s.replace(CHARREF_RE, (_m, ref: string) => replaceCharref(ref));
}

/** `urllib.parse.quote`'s `_ALWAYS_SAFE`. */
const ALWAYS_SAFE =
  "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789_.-~";

/** The safe set `escape_url` passes: gen-delims minus `[]`, sub-delims minus `'`, and `%`. */
const URL_SAFE = ":/?#@!$&()*+,;=%";

/** One entry per byte value, since `quote` works on the UTF-8 encoding. */
const SAFE_BYTES = (() => {
  const table = new Array<boolean>(256).fill(false);
  for (const c of ALWAYS_SAFE + URL_SAFE) table[c.charCodeAt(0)] = true;
  return table;
})();

const UTF8 = new TextEncoder();

const HEX = Array.from({ length: 256 }, (_v, b) =>
  `%${b.toString(16).toUpperCase().padStart(2, "0")}`,
);

/** `urllib.parse.quote(s, safe=":/?#@!$&()*+,;=%")`. */
function quote(s: string): string {
  if (s === "") return s;
  const bytes = UTF8.encode(s);
  let out = "";
  for (const byte of bytes) {
    out += SAFE_BYTES[byte] ? String.fromCharCode(byte) : HEX[byte];
  }
  return out;
}

/** `mistune.util.escape_url`. */
export function escapeUrl(link: string): string {
  return quote(unescape(link));
}
