/**
 * The media-directory walk of `publish_to_wordpress` in
 * `api/src/pipeline/publish.py`, ported to TypeScript.
 *
 * Four lines of Python decide which files the publish hook uploads:
 *
 * ```python
 * if media_dir.is_dir():
 *     for img_file in sorted(media_dir.iterdir()):
 *         if not img_file.is_file():
 *             continue
 * ```
 *
 * and each of them diverges from the obvious JavaScript spelling:
 *
 * * `Path.is_dir()` and `Path.is_file()` **follow symlinks**, so a symlink to
 *   a file is uploaded and a symlink to a directory is not. The natural port,
 *   `readdir(dir, { withFileTypes: true })` plus `entry.isFile()`, answers
 *   from the directory entry rather than from `stat`, which gets both of those
 *   backwards.
 * * both swallow exactly four errnos (`ENOENT`, `ENOTDIR`, `EBADF`, `ELOOP`)
 *   and let every other `OSError` propagate, so a name over `NAME_MAX` raises
 *   out of the publish hook rather than being read as an absent directory. An
 *   embedded NUL is a `ValueError` instead, which is caught and read as
 *   absence.
 * * `os.listdir` decodes names with `os.fsdecode`, which on POSIX is UTF-8
 *   with `surrogateescape`. Node's default decoding replaces an undecodable
 *   byte with U+FFFD, which loses the name and can collide two distinct files
 *   into one.
 * * `sorted()` over `PurePath`s compares code points; `Array.prototype.sort`
 *   compares UTF-16 code units, so an astral filename sorts against everything
 *   from U+E000 up the wrong way.
 *
 * Pinned by `wp-media-walk-parity.json`, generated by
 * `api/scripts/export_media_walk_parity.py` from the real four lines.
 */
import { readdir, stat } from "node:fs/promises"
import type { Stats } from "node:fs"

/** `pathlib._IGNORED_ERRNOS`: what `is_dir()` and `is_file()` read as absence. */
const IGNORED_ERRNOS = new Set(["ENOENT", "ENOTDIR", "EBADF", "ELOOP"])

/**
 * `Path.stat()` behind the `is_dir()` / `is_file()` guard: absence for the
 * four ignored errnos and for a path Python cannot encode, and a throw for
 * anything else.
 *
 * Exported because `is_file()` in the Next.js payload walk
 * (`../nextjs/payload.ts`) swallows the same four errnos and the same
 * `ValueError`.
 */
export async function statOrAbsent(target: string | Buffer): Promise<Stats | null> {
  try {
    return await stat(target)
  } catch (error) {
    const code = (error as NodeJS.ErrnoException).code
    if (code && IGNORED_ERRNOS.has(code)) return null
    // `ValueError: embedded null byte`, which pathlib catches and reads as
    // absence rather than letting it reach the caller.
    if (code === "ERR_INVALID_ARG_VALUE") return null
    throw error
  }
}

/**
 * `os.fsdecode`: UTF-8 with `surrogateescape`, so every byte of a sequence
 * that is not valid UTF-8 becomes U+DC00 plus that byte rather than U+FFFD.
 *
 * CPython reports a decode error over the longest invalid prefix and
 * `surrogateescape` then escapes each byte of it separately, and no byte below
 * 0x80 can ever be part of such a prefix, so escaping one byte at a time and
 * retrying at the next is equivalent to it.
 */
export function decodeFsName(bytes: Uint8Array): string {
  let out = ""
  let index = 0
  while (index < bytes.length) {
    const lead = bytes[index]
    if (lead < 0x80) {
      out += String.fromCharCode(lead)
      index += 1
      continue
    }
    const width =
      lead >= 0xc2 && lead <= 0xdf
        ? 2
        : lead >= 0xe0 && lead <= 0xef
          ? 3
          : lead >= 0xf0 && lead <= 0xf4
            ? 4
            : 0
    const codePoint = width === 0 ? -1 : decodeSequence(bytes, index, width)
    if (codePoint < 0) {
      out += String.fromCharCode(0xdc00 + lead)
      index += 1
      continue
    }
    out += String.fromCodePoint(codePoint)
    index += width
  }
  return out
}

/** The code point of the `width`-byte sequence at `index`, or -1 if invalid. */
function decodeSequence(bytes: Uint8Array, index: number, width: number): number {
  if (index + width > bytes.length) return -1
  let codePoint = bytes[index] & (0xff >> (width + 1))
  for (let offset = 1; offset < width; offset += 1) {
    const byte = bytes[index + offset]
    if ((byte & 0xc0) !== 0x80) return -1
    codePoint = (codePoint << 6) | (byte & 0x3f)
  }
  // Overlong encodings, encoded surrogates and anything past U+10FFFF are all
  // decode errors in Python, not code points.
  const minimum = width === 2 ? 0x80 : width === 3 ? 0x800 : 0x10000
  if (codePoint < minimum) return -1
  if (codePoint > 0x10ffff) return -1
  if (codePoint >= 0xd800 && codePoint <= 0xdfff) return -1
  return codePoint
}

/**
 * Python's `<` between two strings, which compares code points. JavaScript's
 * compares UTF-16 code units, which orders every astral character before
 * U+E000 through U+FFFF instead of after them.
 */
export function comparePythonStrings(left: string, right: string): number {
  let leftIndex = 0
  let rightIndex = 0
  while (leftIndex < left.length && rightIndex < right.length) {
    const leftPoint = left.codePointAt(leftIndex) as number
    const rightPoint = right.codePointAt(rightIndex) as number
    if (leftPoint !== rightPoint) return leftPoint < rightPoint ? -1 : 1
    leftIndex += leftPoint > 0xffff ? 2 : 1
    rightIndex += rightPoint > 0xffff ? 2 : 1
  }
  const leftLeft = left.length - leftIndex
  const rightLeft = right.length - rightIndex
  if (leftLeft === rightLeft) return 0
  return leftLeft < rightLeft ? -1 : 1
}

/** One entry of the walk: what `sorted(media_dir.iterdir())` yielded. */
export interface MediaFile {
  /** `img_file.name`, decoded the way `os.listdir` decodes it. */
  name: string
  /**
   * `img_file` itself, kept as bytes rather than a string so that a name which
   * is not valid UTF-8 still opens. `os.fsencode` would rebuild these bytes
   * from `name`; carrying them is the same thing without a second codec.
   */
  path: Buffer
}

/**
 * `if media_dir.is_dir(): for img_file in sorted(media_dir.iterdir()): if not
 * img_file.is_file(): continue`, as the list of files that survive it.
 *
 * The mimetypes filter that follows in Python is `./mimetypes.ts`, and the
 * upload loop after it is its own ledger item.
 */
export async function listMediaFiles(mediaDir: string): Promise<MediaFile[]> {
  const dir = await statOrAbsent(mediaDir)
  if (!dir?.isDirectory()) return []

  const root = Buffer.from(mediaDir)
  const names = await readdir(root, { encoding: "buffer" })
  const entries = names.map((bytes) => ({
    name: decodeFsName(bytes),
    path: Buffer.concat([root, Buffer.from("/"), bytes]),
  }))
  entries.sort((left, right) => comparePythonStrings(left.name, right.name))

  const files: MediaFile[] = []
  for (const entry of entries) {
    const entryStat = await statOrAbsent(entry.path)
    if (entryStat?.isFile()) files.push(entry)
  }
  return files
}
