/**
 * The upload loop of `publish_to_wordpress` in `api/src/pipeline/publish.py`,
 * ported to TypeScript.
 *
 * Every file the walk found (`./media-walk.ts`) is typed (`./mimetypes.ts`),
 * uploaded, and recorded in a local-URL to WordPress-URL map that is then
 * applied to the rendered document. Four of those twenty lines do not survive
 * the obvious transcription:
 *
 * * `img_info.get("alt_text", title)` falls back to the title only when the
 *   key is *absent*. A manifest entry with `"alt_text": ""` or
 *   `"alt_text": null` sends that value, and `info.alt_text ?? title` gets
 *   both wrong.
 * * `featured_media_id = media.get("id")` can put the variable back to `null`
 *   when the response carries no `id`, which re-arms the `elif` for the next
 *   file. The fallback is really "the first upload that has an id", and an
 *   `id` of `0` is not `None`, so it stops the search.
 * * a `featured_filename` that matches no uploaded file leaves the featured
 *   media unset, and an *empty* `featured_filename` (a manifest url ending in
 *   `/`) is falsy, so it takes the first-image path instead of matching the
 *   file whose name is the empty string.
 * * `str.replace(local, remote)` is `replaceAll`, except that JavaScript reads
 *   `$&`, `` $` ``, `$'`, `$$` and `$1` in the *replacement* as substitution
 *   patterns. A `source_url` holding any of them is corrupted by
 *   `replaceAll`, so the rewrite is spelled `split().join()`.
 *
 * Pinned by `wp-media-upload-parity.json`, generated by
 * `api/scripts/export_media_upload_parity.py` from the real twenty lines.
 *
 * One behaviour is reproduced rather than fixed: the rewrite runs in insertion
 * order over the whole document, so with both `a.png` and `a.png.png` present
 * the shorter local URL rewrites the longer one's prefix and the longer file's
 * `source_url` is never inserted. Logged in `todo.md`; the images stage names
 * files with a timestamp, so no manifest it writes can collide that way.
 */
import { readFile } from "node:fs/promises"

import { listMediaFiles, type MediaFile } from "./media-walk"
import { guessTypeFromFilename } from "./mimetypes"
import type { ManifestImage, ManifestImageIndex } from "./publish-metadata"

/**
 * `WordPressClient.upload_media` as far as this loop can see it. Narrower than
 * the class so a test can stand in for the network without a fake site.
 */
export interface MediaUploader {
  uploadMedia(
    imageBytes: Uint8Array<ArrayBuffer>,
    filename: string,
    mimeType: string,
    altText: unknown,
  ): Promise<unknown>
}

/** Python's name for the type of a decoded JSON value, for `AttributeError`. */
function pythonTypeName(value: unknown): string {
  if (value === null) return "NoneType"
  if (Array.isArray(value)) return "list"
  switch (typeof value) {
    case "string":
      return "str"
    case "boolean":
      return "bool"
    // `1.0` decodes to a float in Python and to an integer here, so a
    // whole-number float is named `int` in this message and `float` in
    // Python's. The message is the only thing that differs.
    case "number":
      return Number.isInteger(value) ? "int" : "float"
    default:
      return "object"
  }
}

/**
 * `media.get(key, fallback)`. The publish hook never checks that the client
 * returned a JSON object, so a WordPress that answers with a list or a bare
 * `null` raises `AttributeError` out of the loop and into the hook's `_fail`.
 * The message is Python's so that the recorded failure reads the same.
 */
function mediaGet(media: unknown, key: string, fallback: unknown = null): unknown {
  if (media === null || typeof media !== "object" || Array.isArray(media)) {
    throw new TypeError(`'${pythonTypeName(media)}' object has no attribute 'get'`)
  }
  const record = media as Record<string, unknown>
  return Object.hasOwn(record, key) ? record[key] : fallback
}

export interface MediaUploadOptions {
  /** `post_id`, which is the media directory's name and the URL prefix. */
  postId: string
  /** The frontmatter title, which is the default alt text. */
  title: string
  /** `manifest_by_file` and `featured_filename` from `indexManifestImages`. */
  manifest: ManifestImageIndex
  client: MediaUploader
}

export interface MediaUploadResult {
  /**
   * `image_map`: `/media/<post_id>/<name>` to the upload's `source_url`, in
   * upload order. The value is whatever the response held, so a `source_url`
   * that is not a string reaches `rewriteImageUrls` and raises there, exactly
   * as `str.replace` does.
   */
  imageMap: Map<string, unknown>
  /** `featured_media_id`: `media["id"]` of the featured upload, or null. */
  featuredMediaId: unknown
}

/**
 * The body of `for img_file in sorted(media_dir.iterdir())`, over the files
 * the walk yielded: the mime filter, the upload, and the featured-media
 * resolution.
 */
export async function uploadMediaFiles(
  files: readonly MediaFile[],
  options: MediaUploadOptions,
): Promise<MediaUploadResult> {
  const { postId, title, manifest, client } = options
  const imageMap = new Map<string, unknown>()
  let featuredMediaId: unknown = null

  for (const file of files) {
    const [mime] = guessTypeFromFilename(file.name)
    if (!mime || !mime.startsWith("image/")) continue

    const info: ManifestImage = manifest.byFile.get(file.name) ?? {}
    const alt = Object.hasOwn(info, "alt_text") ? info.alt_text : title

    // `Buffer` is typed `Uint8Array<ArrayBufferLike>`; the copy is what gives
    // the client the `Uint8Array<ArrayBuffer>` its body type asks for.
    const bytes = new Uint8Array(await readFile(file.path))
    const media = await client.uploadMedia(bytes, file.name, mime, alt)

    imageMap.set(`/media/${postId}/${file.name}`, mediaGet(media, "source_url", ""))

    if (manifest.featuredFilename && file.name === manifest.featuredFilename) {
      featuredMediaId = mediaGet(media, "id")
    } else if (featuredMediaId === null && !manifest.featuredFilename) {
      featuredMediaId = mediaGet(media, "id")
    }
  }

  return { imageMap, featuredMediaId }
}

/**
 * `for local, remote in image_map.items(): wp_html = wp_html.replace(local, remote)`.
 *
 * `split().join()` rather than `replaceAll()` because the remote URL is data,
 * not a replacement pattern.
 */
export function rewriteImageUrls(html: string, imageMap: Map<string, unknown>): string {
  let result = html
  for (const [local, remote] of imageMap) {
    if (typeof remote !== "string") {
      // `str.replace(local, 7)` is a `TypeError`, raised after every upload
      // has already happened. Same message, same timing.
      throw new TypeError(
        // Argument Clinic names the `None` singleton `None` here, where
        // `AttributeError` above names its type `NoneType`.
        `replace() argument 2 must be str, not ${
          remote === null ? "None" : pythonTypeName(remote)
        }`,
      )
    }
    result = result.split(local).join(remote)
  }
  return result
}

/**
 * The whole media sweep: `if media_dir.is_dir(): for img_file in
 * sorted(media_dir.iterdir())`, its mime filter, and the upload loop.
 */
export async function sweepMediaDirectory(
  mediaDir: string,
  options: MediaUploadOptions,
): Promise<MediaUploadResult> {
  return uploadMediaFiles(await listMediaFiles(mediaDir), options)
}
