/**
 * Parity tests for the `mimetypes.guess_type` port (ledger item
 * 5.3c-iii-b-1-c-ii-1).
 *
 * The oracle in `data/wp-mimetypes-parity.json` is written by
 * `api/scripts/export_mimetypes_parity.py` running inside `python:3.12-slim`,
 * which is the image the deployed `api` and `worker` services are built from.
 * It carries the four tables verbatim as well as the answers, so this file
 * checks the port's tables against Python's rather than trusting a
 * transcription. Nothing here asserts a hand-written expectation except the
 * provenance checks at the top and the four controls at the bottom.
 */
import { describe, expect, it } from "vitest"

import parity from "./data/wp-mimetypes-parity.json"
import {
  COMMON_TYPES,
  ENCODINGS_MAP,
  SUFFIX_MAP,
  TYPES_MAP,
  guessTypeFromFilename,
  splitext,
} from "./mimetypes"

interface GuessCase {
  name: string
  url: string
  strict: boolean
  type: string | null
  encoding: string | null
  isImage: boolean
}

const cases = parity.cases as GuessCase[]

describe("the wp-mimetypes oracle", () => {
  it("was generated by the deployed interpreter", () => {
    expect(parity.pythonVersion.startsWith("3.12.")).toBe(true)
  })

  it("was generated with no knownfile on the host", () => {
    expect(parity.knownfilesPresent).toEqual([])
  })

  it("covers every case with a single path component", () => {
    expect(cases.length).toBeGreaterThan(90)
    for (const row of cases) {
      expect(row.url).not.toContain("/")
    }
  })

  it("covers both strict and non-strict lookups", () => {
    expect(cases.some((row) => row.strict)).toBe(true)
    expect(cases.some((row) => !row.strict)).toBe(true)
  })
})

describe("the ported tables match Python's", () => {
  it("types_map", () => {
    expect([...TYPES_MAP]).toEqual(parity.typesMap.map(([k, v]) => [k, v]))
  })

  it("common_types", () => {
    expect([...COMMON_TYPES]).toEqual(parity.commonTypes.map(([k, v]) => [k, v]))
  })

  it("encodings_map", () => {
    expect([...ENCODINGS_MAP]).toEqual(
      parity.encodingsMap.map(([k, v]) => [k, v]),
    )
  })

  it("suffix_map", () => {
    expect([...SUFFIX_MAP]).toEqual(parity.suffixMap.map(([k, v]) => [k, v]))
  })
})

describe("guessTypeFromFilename matches mimetypes.guess_type", () => {
  for (const row of cases) {
    it(`${row.name}${row.strict ? "" : " (strict=false)"}`, () => {
      expect(guessTypeFromFilename(row.url, row.strict)).toEqual([
        row.type,
        row.encoding,
      ])
    })
  }
})

describe("the image predicate the media sweep applies", () => {
  for (const row of cases) {
    it(`${row.name}${row.strict ? "" : " (strict=false)"}`, () => {
      const [mime] = guessTypeFromFilename(row.url, row.strict)
      expect(Boolean(mime) && mime!.startsWith("image/")).toBe(row.isImage)
    })
  }
})

describe("controls", () => {
  it("refuses a path rather than parsing it as a URL", () => {
    expect(() => guessTypeFromFilename("dir/a.png")).toThrow(TypeError)
  })

  it("skips leading dots when splitting the extension", () => {
    expect(splitext(".png")).toEqual([".png", ""])
    expect(splitext("..png")).toEqual(["..png", ""])
    expect(splitext(".a.png")).toEqual([".a", ".png"])
  })

  it("does not reapply suffix_map after stripping the encoding", () => {
    expect(guessTypeFromFilename("a.svgz")).toEqual(["image/svg+xml", "gzip"])
    expect(guessTypeFromFilename("a.svgz.gz")).toEqual([null, "gzip"])
  })

  it("skips the .webp files the images stage writes", () => {
    expect(TYPES_MAP.has(".webp")).toBe(false)
    expect(guessTypeFromFilename("featured-082326-abc.webp")).toEqual([
      null,
      null,
    ])
  })
})
