/**
 * The pure metadata helpers of `publish_to_wordpress` in
 * `api/src/pipeline/publish.py`, ported to TypeScript.
 *
 * Two pieces of the publish hook decide what the WordPress post is called and
 * which uploaded image becomes the featured one, and both run before anything
 * touches the network:
 *
 * * `_extract_frontmatter` splits the ready content into a flat key-value map
 *   and a body. Every primitive it uses diverges between the two languages.
 *   Python's `\s` holds `\x1c`-`\x1f` and `\x85` and omits `﻿`, where
 *   JavaScript's `\s` does the reverse, so a draft whose fence line carries a
 *   BOM parses in JavaScript and not in Python; `str.strip()` with no argument
 *   uses that same Python class rather than `String.trim()`'s; and
 *   `.strip('"').strip("'")` strips a *set* of characters at both ends in a
 *   fixed order, so `'"Hello"'` loses the single quotes first and keeps the
 *   double ones.
 * * the loop that indexes `post.image_manifest` by filename and remembers the
 *   featured entry. The last matching entry wins in both maps independently,
 *   so a featured entry followed by an inline one with the same filename
 *   leaves the filename marked featured while the map holds the inline entry.
 *
 * Both are pinned by `wp-publish-metadata-parity.json`, generated by
 * `api/scripts/export_wp_publish_metadata_parity.py` from the real Python
 * function.
 *
 * Three input shapes raise in Python and are treated as empty here rather than
 * reproduced: an `image_manifest` that is a non-empty non-object (`.get` on a
 * list is an `AttributeError`), an `images` value that is not a list (every
 * element of a string or a dict fails the same `.get`), and a manifest entry
 * whose `url` is JSON null (`"/" in None` is a `TypeError`). The images stage
 * only ever writes an object of objects with string urls, so none of the three
 * is reachable from the column this reads.
 */
import { PY_WHITESPACE, pythonStrip } from "../textstat"

/**
 * `re.match(r"^---\s*\n(.*?)\n---\s*\n(.*)$", content, re.DOTALL)`. `.` under
 * `DOTALL` is every character, which is `[\s\S]` here because JavaScript's `.`
 * excludes more than Python's.
 */
const FRONTMATTER = new RegExp(
  `^---[${PY_WHITESPACE}]*\\n([\\s\\S]*?)\\n---[${PY_WHITESPACE}]*\\n([\\s\\S]*)$`,
  "u",
)

/**
 * `str.strip(chars)`, which removes every leading and trailing character that
 * is in `chars` rather than the substring `chars`.
 */
function stripChars(text: string, chars: string): string {
  let start = 0
  let end = text.length
  while (start < end && chars.includes(text[start])) start += 1
  while (end > start && chars.includes(text[end - 1])) end -= 1
  return text.slice(start, end)
}

export interface Frontmatter {
  /**
   * A `Map` rather than an object because the keys come from the model's
   * output: `__proto__` is an ordinary dict key in Python and would be a
   * prototype write here.
   */
  meta: Map<string, string>
  body: string
}

/** `_extract_frontmatter`: YAML frontmatter as simple key-value pairs. */
export function extractFrontmatter(content: string): Frontmatter {
  const match = FRONTMATTER.exec(content)
  if (!match) return { meta: new Map(), body: content }

  const meta = new Map<string, string>()
  for (const line of match[1].split("\n")) {
    const colon = line.indexOf(":")
    if (colon === -1) continue
    const key = pythonStrip(line.slice(0, colon))
    const value = stripChars(stripChars(pythonStrip(line.slice(colon + 1)), '"'), "'")
    meta.set(key, value)
  }
  return { meta, body: match[2] }
}

/** One entry of `image_manifest.images`, as the images stage writes it. */
export type ManifestImage = Record<string, unknown>

export interface ManifestImageIndex {
  /** `manifest_by_file`: filename to manifest entry, last entry winning. */
  byFile: Map<string, ManifestImage>
  /** `featured_filename`: the last entry flagged featured, if any. */
  featuredFilename: string | null
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value)
}

/** The `manifest_by_file` / `featured_filename` loop of `publish_to_wordpress`. */
export function indexManifestImages(
  manifest: Record<string, unknown> | null | undefined,
): ManifestImageIndex {
  const images = isRecord(manifest) ? manifest.images : undefined
  const byFile = new Map<string, ManifestImage>()
  let featuredFilename: string | null = null

  if (!Array.isArray(images)) return { byFile, featuredFilename }

  for (const entry of images) {
    if (!isRecord(entry)) continue
    const url = typeof entry.url === "string" ? entry.url : ""
    // `url.rsplit("/", 1)[-1]`, which is the whole string when there is no
    // slash, so the guard Python spells out changes nothing.
    const filename = url.slice(url.lastIndexOf("/") + 1)
    byFile.set(filename, entry)
    if (entry.placement === "featured" || entry.type === "featured") {
      featuredFilename = filename
    }
  }
  return { byFile, featuredFilename }
}
