import { describe, expect, it } from "vitest";

import parity from "./data/wp-html-list-parity.json";
import { UnportedMarkdownError, markdownToWpHtml } from "./wp-html";

/**
 * `markdown_to_wp_html`'s list handling, replayed against the real Python
 * function's output. `parity.cases` is generated by
 * `api/scripts/export_wp_html_list_parity.py`; nothing in this file asserts an
 * expectation that was written by hand.
 *
 * The renderer for a list is six lines of format string. Everything that can go
 * wrong lives in `list_parser.py`: the continuation width derived from the first
 * item's text, the per-item break scanner compiled out of six other block
 * patterns, and the tight/loose rule that decides whether an item body gets a
 * paragraph wrapper at all.
 */

type Case = { name: string; markdown: string; html: string };
const cases = parity.cases as Case[];

describe("markdownToWpHtml, lists", () => {
  it("has an oracle generated from the Python implementation", () => {
    expect(parity.source).toBe(
      "api/src/services/wp_html.py::markdown_to_wp_html",
    );
    expect(cases.length).toBeGreaterThanOrEqual(70);
  });

  it.each(cases.map((c): [string, Case] => [c.name, c]))(
    "matches Python byte for byte: %s",
    (_name, testCase) => {
      expect(markdownToWpHtml(testCase.markdown)).toBe(testCase.html);
    },
  );
});

describe("the list oracle has teeth", () => {
  /**
   * Negative controls: each is a plausible way to get `parse_list` wrong that
   * the replay above would catch, asserted here so the corpus is not merely a
   * set of cases any markdown parser would pass.
   */

  it("emits no paragraph wrapper inside a tight list", () => {
    expect(markdownToWpHtml("- one\n- two\n")).toBe(
      "<!-- wp:list -->\n<ul><li>one</li>\n<li>two</li>\n</ul>\n" +
        "<!-- /wp:list -->\n\n",
    );
  });

  it("wraps item bodies in paragraphs once a blank line makes the list loose", () => {
    // The same two items with one blank line between them. A port that skipped
    // `_transform_tight_list` would render both forms identically.
    const loose = markdownToWpHtml("- one\n\n- two\n");
    expect(loose).toContain("<li><!-- wp:paragraph -->\n<p>one</p>");
    expect(markdownToWpHtml("- one\n- two\n")).not.toContain("wp:paragraph");
  });

  it("makes an outer list loose without making its nested list loose", () => {
    // `_transform_tight_list` recurses into a nested `list` token, so the inner
    // items keep their `block_text` bodies while the outer ones do not.
    const html = markdownToWpHtml("- one\n  - nested\n\n- two\n");
    expect(html).toContain("<ul><li>nested</li>\n</ul>");
    expect(html).toContain("<p>two</p>");
  });

  it("marks an ordered list ordered and carries a non-one start", () => {
    expect(markdownToWpHtml("1. one\n")).toContain(
      '<!-- wp:list {"ordered":true} -->',
    );
    // `start` reaches the token but this renderer never prints it, which is why
    // the two forms below are byte identical.
    expect(markdownToWpHtml("3. three\n")).toBe(markdownToWpHtml("1. three\n"));
  });

  it("keeps a marker change from continuing the same list", () => {
    // `_get_list_bullet` compiles the item pattern around the first marker, so a
    // `+` cannot be a `-` list's second item.
    const html = markdownToWpHtml("- one\n+ two\n");
    expect(html.split("<!-- wp:list -->").length - 1).toBe(2);
  });

  it("prefers a thematic break to a list for three spaced dashes", () => {
    expect(markdownToWpHtml("- - -\n")).toContain("wp:separator");
    expect(markdownToWpHtml("- - -\n")).not.toContain("wp:list");
  });

  it("lets an ordered one interrupt a paragraph but not an ordered three", () => {
    // CommonMark Example 304. Both go through `append_paragraph`, and only the
    // one that declines produces a list.
    expect(markdownToWpHtml("Para.\n1. item\n")).toContain("wp:list");
    expect(markdownToWpHtml("Para.\n3. item\n")).not.toContain("wp:list");
  });

  it("refuses to let an empty item interrupt a paragraph", () => {
    // CommonMark Example 285.
    expect(markdownToWpHtml("Para.\n-\n")).not.toContain("wp:list");
  });

  it("emits the list before a block that broke it out", () => {
    // The break scanner parses the fence on the *outer* state and the list is
    // then spliced in at the index it recorded, so document order survives a
    // mechanism that writes backwards.
    const html = markdownToWpHtml("- one\n```\ncode\n```\n");
    expect(html.indexOf("<!-- wp:list -->")).toBeLessThan(
      html.indexOf("<!-- wp:code -->"),
    );
  });

  it("keeps a fence indented to the continuation width inside the item", () => {
    // Compare the case above: two spaces of indent make the same fence part of
    // the item rather than the block that ends the list.
    const html = markdownToWpHtml("- one\n  ```\n  code\n  ```\n");
    expect(html.indexOf("<!-- wp:code -->")).toBeLessThan(
      html.indexOf("</ul>"),
    );
  });

  it("treats five spaces after the marker as indented code", () => {
    // `_compile_continue_width` keeps four of the five, so the item body is a
    // code block rather than text indented by five.
    expect(markdownToWpHtml("-     code\n")).toContain(
      '<pre class="wp-block-code">',
    );
    expect(markdownToWpHtml("-    text\n")).not.toContain("wp-block-code");
  });

  it("pulls an unindented following line into the item", () => {
    expect(markdownToWpHtml("- one\ntwo\n")).toContain("<li>one\ntwo</li>");
  });

  it("nests lists to six levels and stops nesting at the seventh", () => {
    const seven =
      "- a\n  - b\n    - c\n      - d\n        - e\n          - f\n            - g\n";
    expect(markdownToWpHtml(seven).split("<ul>").length - 1).toBe(6);
  });

  it("still refuses the rules that are not ported yet, inside a list item", () => {
    // An item reparses its body with the full rule set, so an unported rule in
    // an item must stop the converter rather than flatten to text. This read
    // `- <div>raw</div>` until 5.3c-iii-b-1-b-ii-3-a ported `raw_html`.
    expect(() =>
      markdownToWpHtml("- [label]: https://example.com\n"),
    ).toThrowError(UnportedMarkdownError);
  });
});
