import { describe, expect, it } from "vitest";

import parity from "./data/wp-html-quote-parity.json";
import { markdownToWpHtml } from "./wp-html";

/**
 * `markdown_to_wp_html`'s block-quote handling, replayed against the real
 * Python function's output. `parity.cases` is generated by
 * `api/scripts/export_wp_html_quote_parity.py`; nothing in this file asserts an
 * expectation that was written by hand.
 *
 * The renderer for a quote is three lines of format string. Everything that can
 * go wrong lives in `extract_block_quote`, which decides how far the quote
 * reaches and whether an unmarked line continues it.
 */

type Case = { name: string; markdown: string; html: string };
const cases = parity.cases as Case[];

describe("markdownToWpHtml, block quotes", () => {
  it("has an oracle generated from the Python implementation", () => {
    expect(parity.source).toBe(
      "api/src/services/wp_html.py::markdown_to_wp_html",
    );
    expect(cases.length).toBeGreaterThanOrEqual(50);
  });

  it.each(cases.map((c): [string, Case] => [c.name, c]))(
    "matches Python byte for byte: %s",
    (_name, testCase) => {
      expect(markdownToWpHtml(testCase.markdown)).toBe(testCase.html);
    },
  );
});

describe("the quote oracle has teeth", () => {
  /**
   * Negative controls: each is a plausible way to get `extract_block_quote`
   * wrong that the replay above would catch, asserted here so the corpus is not
   * merely a set of cases any markdown parser would pass.
   */

  it("pulls an unmarked following line into the quote", () => {
    // Laziness. A port that ended the quote at the last `>` would put "two" in
    // a sibling paragraph instead of inside the blockquote.
    const html = markdownToWpHtml("> one\ntwo\n");
    expect(html).toBe(
      "<!-- wp:quote -->\n" +
        '<blockquote class="wp-block-quote"><!-- wp:paragraph -->\n' +
        "<p>one\ntwo</p>\n" +
        "<!-- /wp:paragraph -->\n\n</blockquote>\n" +
        "<!-- /wp:quote -->\n\n",
    );
  });

  it("stops being lazy after a marked blank line", () => {
    // CommonMark Example 249. The same input as above plus a `>` on its own
    // line puts the following text outside the quote entirely.
    const html = markdownToWpHtml("> one\n>\ntwo\n");
    expect(html.indexOf("<p>two</p>")).toBeGreaterThan(
      html.indexOf("<!-- /wp:quote -->"),
    );
  });

  it("refuses laziness when the quote opens a code block", () => {
    // The require-marker branch: an indented first line makes the quote strict,
    // so the unmarked line below it is not part of the quote.
    const html = markdownToWpHtml(">     code\ntext\n");
    expect(html).toContain('<pre class="wp-block-code">');
    expect(html.indexOf("<p>text</p>")).toBeGreaterThan(
      html.indexOf("<!-- /wp:quote -->"),
    );
  });

  it("emits the quote before a block that broke it out", () => {
    // The lazy branch parses the thematic break on the *outer* state and then
    // prepends the quote token, so document order survives a mechanism that
    // reads backwards.
    const html = markdownToWpHtml("> quoted\n***\n");
    expect(html.indexOf("<!-- wp:quote -->")).toBeLessThan(
      html.indexOf("<!-- wp:separator -->"),
    );
  });

  it("does not break the quote out on a heading", () => {
    // `atx_heading` is not in the break list, so an unmarked `## Title` is a
    // lazy line: it joins the quote's body and only then becomes a heading, so
    // the heading lands *inside* the blockquote. Compare the thematic break
    // above, which is in the break list and lands outside it. Getting the break
    // list wrong swaps the two, and nothing in the renderer would show it.
    const html = markdownToWpHtml("> quoted\n## Title\n");
    expect(html.indexOf("<!-- wp:heading -->")).toBeLessThan(
      html.indexOf("</blockquote>"),
    );
    expect(html.indexOf("<!-- wp:separator -->")).toBe(-1);
  });

  it("nests quotes to six levels and stops nesting at the seventh", () => {
    const six = markdownToWpHtml("> > > > > > deep\n");
    expect(six.split("<!-- wp:quote -->").length - 1).toBe(6);
    const seven = markdownToWpHtml("> > > > > > > deep\n");
    expect(seven.split("<!-- wp:quote -->").length - 1).toBe(6);
    expect(seven).toContain("<p>&gt; deep</p>".replace("&gt;", ">"));
  });

  it("strips exactly one space after the marker", () => {
    expect(markdownToWpHtml(">    quoted\n")).toContain("<p>quoted</p>");
    expect(markdownToWpHtml(">quoted\n")).toContain("<p>quoted</p>");
  });

  it("treats an angle bracket mid line as text", () => {
    expect(markdownToWpHtml("a > b\n")).toBe(
      "<!-- wp:paragraph -->\n<p>a > b</p>\n<!-- /wp:paragraph -->\n\n",
    );
  });

  it("keeps the marker inert once the line is indented four spaces", () => {
    expect(markdownToWpHtml("Para.\n\n    > quoted\n")).toContain(
      '<pre class="wp-block-code">',
    );
  });

  it("reparses its body with the whole rule set, inside a quote", () => {
    // A quote reparses its body in a child state, so a rule that works at the
    // top level has to work here too. This asserted a refusal while the rules
    // were still landing: `> - item` until 5.3c-iii-b-1-b-ii-2 ported `list`,
    // `> <div>raw</div>` until -ii-3-a ported `raw_html`,
    // `> [label]: https://example.com` until -ii-3-b-2 ported `ref_link`,
    // `> an *emphasised* word` until -iii-c ported `emphasis`, and this input
    // until -iii-d ported `link`, which finished the port.
    expect(markdownToWpHtml("> a [link](/b) here\n")).toBe(
      "<!-- wp:quote -->\n" +
        '<blockquote class="wp-block-quote"><!-- wp:paragraph -->\n' +
        '<p>a <a href="/b">link</a> here</p>\n<!-- /wp:paragraph -->\n\n' +
        "</blockquote>\n<!-- /wp:quote -->\n\n",
    );
  });
});
