import { describe, expect, it } from "vitest";

import parity from "./data/wp-html-html-parity.json";
import { UnportedMarkdownError, markdownToWpHtml } from "./wp-html";

/**
 * `markdown_to_wp_html`'s raw-HTML handling, replayed against the real Python
 * function's output. `parity.cases` is generated by
 * `api/scripts/export_wp_html_html_parity.py`; nothing in this file asserts an
 * expectation that was written by hand.
 *
 * The renderer for an HTML block is one format string. Everything that can go
 * wrong lives in `parse_raw_html`, which picks between seven CommonMark rules
 * off the few characters after the `<` and can also decline outright.
 */

type Case = { name: string; markdown: string; html: string };
type Decline = { name: string; markdown: string; raises: string; message: string };

const cases = parity.cases as Case[];
const declines = parity.declines as Decline[];

describe("markdownToWpHtml, raw HTML blocks", () => {
  it("has an oracle generated from the Python implementation", () => {
    expect(parity.source).toBe(
      "api/src/services/wp_html.py::markdown_to_wp_html",
    );
    expect(cases.length).toBeGreaterThanOrEqual(80);
  });

  it.each(cases.map((c): [string, Case] => [c.name, c]))(
    "matches Python byte for byte: %s",
    (_name, testCase) => {
      expect(markdownToWpHtml(testCase.markdown)).toBe(testCase.html);
    },
  );
});

describe("rule 7's decline path", () => {
  /**
   * These are the inputs where `parse_raw_html` returns None and the line falls
   * through to the paragraph fallback. There is no rendered output to compare:
   * the inline parse produces an `inline_html` token and `_GutenbergRenderer`
   * has no method for it, so the real function raises `AttributeError`. The
   * oracle records that, and the port reaches the same layer and throws there
   * because the inline rules are ledger item -b-iii.
   */

  it("records four declines that crash the real renderer", () => {
    expect(declines).toHaveLength(5);
    for (const decline of declines) {
      expect(decline.raises).toBe("AttributeError");
      expect(decline.message).toContain("inline_html");
    }
  });

  it.each(declines.map((d): [string, Decline] => [d.name, d]))(
    "falls through to the inline layer: %s",
    (_name, decline) => {
      let thrown: unknown;
      try {
        markdownToWpHtml(decline.markdown);
      } catch (error) {
        thrown = error;
      }
      expect(thrown).toBeInstanceOf(UnportedMarkdownError);
      expect((thrown as UnportedMarkdownError).rule).toBe("inline_html");
    },
  );
});

describe("the raw-HTML oracle has teeth", () => {
  /**
   * Negative controls: each is a plausible way to get `parse_raw_html` wrong
   * that the replay above would catch, asserted here so the corpus is not
   * merely a set of cases any markdown parser would pass.
   */

  it("lets a comment swallow a blank line", () => {
    // Rules 1 to 5 scan for an end marker, not for a blank line. A port that
    // used the blank-line scan for every rule would cut this comment in two.
    // The raw text keeps the newline the block ended on and the renderer adds
    // its own, so there is a blank line before the closing Gutenberg comment.
    expect(markdownToWpHtml("<!-- one\n\ntwo -->\n")).toBe(
      "<!-- wp:html -->\n<!-- one\n\ntwo -->\n\n<!-- /wp:html -->\n\n",
    );
  });

  it("stops a div at the blank line, not at its closing tag", () => {
    // Rule 6 ignores `</div>` entirely: the block ends at the blank line, so
    // the closing tag is inside the raw text and "After." is a paragraph.
    expect(markdownToWpHtml("<div>\ncontent\n</div>\n\nAfter.\n")).toBe(
      "<!-- wp:html -->\n<div>\ncontent\n</div>\n\n<!-- /wp:html -->\n\n" +
        "<!-- wp:paragraph -->\n<p>After.</p>\n<!-- /wp:paragraph -->\n\n",
    );
  });

  it("does not parse markdown inside a block tag", () => {
    const html = markdownToWpHtml("<div>\n## Not a heading\n</div>\n");
    expect(html).not.toContain("<h2>");
    expect(html).toContain("## Not a heading");
  });

  it("splits a block tag at an interior blank line", () => {
    // The same input with blank lines around the heading is three blocks, and
    // the middle one is a real heading. This is the counterpart of the test
    // above and pins the blank-line boundary rather than the tag boundary.
    const html = markdownToWpHtml("<div>\n\n## Heading\n\n</div>\n");
    expect(html).toContain("<h2>Heading</h2>");
    expect(html.indexOf("<div>")).toBeLessThan(html.indexOf("<h2>"));
    expect(html.indexOf("</div>")).toBeGreaterThan(html.indexOf("<h2>"));
  });

  it("treats an unclosed script as running to the end of the document", () => {
    expect(markdownToWpHtml("<script>\nvar x = 1;\n")).toBe(
      "<!-- wp:html -->\n<script>\nvar x = 1;\n\n<!-- /wp:html -->\n\n",
    );
  });

  it("matches a block tag on its name alone, before any closing angle", () => {
    // `<div` with no `>` is still rule 6. A port that required a complete tag
    // would fall through to rule 7, which declines, and emit a paragraph.
    expect(markdownToWpHtml("<div\ncontent\n")).toContain("<!-- wp:html -->");
  });

  it("does not treat a tag whose name merely starts with a block tag as one", () => {
    // `<divx>` is not `<div>`. Rule 6 must compare the whole name.
    expect(markdownToWpHtml("<divx>\ncontent\n")).toBe(
      "<!-- wp:html -->\n<divx>\ncontent\n\n<!-- /wp:html -->\n\n",
    );
  });

  it("lowercases the tag name before the table lookup", () => {
    expect(markdownToWpHtml("<DIV>\ncontent\n</DIV>\n")).toContain(
      "<!-- wp:html -->",
    );
  });

  it("leaves a tag inside indented code alone", () => {
    expect(markdownToWpHtml("Para.\n\n    <div>\n")).toContain(
      "wp-block-code",
    );
  });

  it("does not let a closed block tag break a lazy block-quote continuation", () => {
    // `block_html` is in `extract_block_quote`'s break set, but `BLOCK_HTML`
    // requires whitespace or a line end straight after the tag name, and
    // `<div>` has `>` there. So the line is a lazy continuation and the HTML
    // block is parsed inside the quote.
    const html = markdownToWpHtml("> quoted\n<div>\nx\n");
    expect(html.indexOf("<!-- wp:html -->")).toBeLessThan(
      html.indexOf("</blockquote>"),
    );
  });

  it("lets a block tag followed by a space break a lazy continuation", () => {
    // The same tag with an attribute does satisfy `BLOCK_HTML`, so here the
    // quote ends and the HTML block is a sibling. This pins the whitespace
    // requirement rather than the tag name.
    const html = markdownToWpHtml('> quoted\n<div class="x">\nx\n');
    expect(html.indexOf("</blockquote>")).toBeLessThan(
      html.indexOf("<!-- wp:html -->"),
    );
  });

  it("lets a comment break a lazy block-quote continuation", () => {
    // `BLOCK_HTML`'s comment alternative has no whitespace requirement, so a
    // comment ends the quote where `<div>` did not.
    const html = markdownToWpHtml("> quoted\n<!-- c -->\n");
    expect(html.indexOf("</blockquote>")).toBeLessThan(
      html.indexOf("<!-- wp:html -->"),
    );
  });
});
