import { describe, expect, it } from "vitest";

import parity from "./data/wp-html-inline-link-parity.json";
import {
  MissingRendererError,
  markdownToWpHtml,
  parseInlineTokens,
  renderTokens,
  type RefLink,
  type Token,
} from "./wp-html";

/**
 * The inline `link` and `image` rules, `parse_link_label`, `parse_link_text`,
 * `parse_link`, the `in_link` / `in_image` guards, the `ref_links` lookup and
 * the `image` renderer method, replayed against the real Python
 * implementation. Every expectation in
 * `data/wp-html-inline-link-parity.json` is generated by
 * `api/scripts/export_wp_html_inline_link_parity.py`; nothing here asserts a
 * value written by hand except the controls at the bottom, which were added
 * after the replay passed.
 *
 * Four corpora:
 *
 * * `html_cases` are whole documents through `markdown_to_wp_html`.
 * * `raising_cases` are the documents whose paragraph ends up holding a tag,
 *   which `_GutenbergRenderer` has no method for, so they pin the exception.
 * * `token_cases` are single inline strings through mistune's own
 *   `InlineParser.__call__`, with the env supplied explicitly. A reference link
 *   carries `ref` and `label` fields the renderer drops, and the nesting flags
 *   are only visible as a token that did *not* become a link.
 * * `render_cases` are single tokens through `_GutenbergRenderer.image` and
 *   `.link`, which is how the empty-children and title branches are pinned.
 */

type HtmlCase = { name: string; markdown: string; html: string };
type RaisingCase = {
  name: string;
  markdown: string;
  error: { type: string; message: string };
};
type TokenCase = {
  name: string;
  src: string;
  ref_links: Record<string, RefLink>;
  tokens: Token[];
};
type RenderCase = { name: string; method: string; token: Token; html: string };

const htmlCases = parity.html_cases as HtmlCase[];
const raisingCases = parity.raising_cases as RaisingCase[];
const tokenCases = parity.token_cases as TokenCase[];
const renderCases = parity.render_cases as RenderCase[];

const refLinksOf = (c: TokenCase) => new Map(Object.entries(c.ref_links));

describe("markdownToWpHtml, the link and image rules", () => {
  it("has an oracle generated from the Python implementation", () => {
    expect(parity.source).toBe(
      "api/src/services/wp_html.py::markdown_to_wp_html",
    );
    expect(parity.token_source).toBe("mistune.InlineParser.__call__");
    expect(htmlCases.length).toBeGreaterThanOrEqual(80);
    expect(raisingCases.length).toBeGreaterThanOrEqual(2);
    expect(tokenCases.length).toBeGreaterThanOrEqual(20);
    expect(renderCases.length).toBeGreaterThanOrEqual(6);
    // A corpus of links that all resolve would prove only half the rule, whose
    // decline path is the only reason the scan loop's fallback exists.
    expect(htmlCases.filter((c) => c.html.includes("<a href")).length).toBeGreaterThanOrEqual(40);
    expect(
      htmlCases.filter((c) => !c.html.includes("<a href") && !c.html.includes("wp:image"))
        .length,
    ).toBeGreaterThanOrEqual(10);
  });

  it.each(htmlCases.map((c): [string, HtmlCase] => [c.name, c]))(
    "matches Python's HTML byte for byte: %s",
    (_name, testCase) => {
      expect(markdownToWpHtml(testCase.markdown)).toBe(testCase.html);
    },
  );

  it.each(raisingCases.map((c): [string, RaisingCase] => [c.name, c]))(
    "raises where Python's renderer raises: %s",
    (_name, testCase) => {
      // Python's `BaseRenderer._get_method` raises
      // `AttributeError: No renderer "'inline_html'"`.
      expect(testCase.error.type).toBe("AttributeError");
      expect(testCase.error.message).toBe("No renderer \"'inline_html'\"");
      try {
        markdownToWpHtml(testCase.markdown);
        expect.unreachable("expected a MissingRendererError");
      } catch (error) {
        expect(error).toBeInstanceOf(MissingRendererError);
        expect((error as MissingRendererError).tokenType).toBe("inline_html");
      }
    },
  );

  it.each(tokenCases.map((c): [string, TokenCase] => [c.name, c]))(
    "matches mistune's inline token stream: %s",
    (_name, testCase) => {
      expect(parseInlineTokens(testCase.src, refLinksOf(testCase))).toEqual(
        testCase.tokens,
      );
    },
  );

  it.each(renderCases.map((c): [string, RenderCase] => [c.name, c]))(
    "matches the Python renderer method: %s",
    (_name, testCase) => {
      expect(renderTokens([testCase.token])).toBe(testCase.html);
    },
  );
});

describe("hand written controls", () => {
  /**
   * Each value below was read off the real `markdown_to_wp_html` before it was
   * written here, the same way the corpus was. They name the behaviours the
   * replay would still pass without, so a rewrite that broke one has something
   * to fail against by name.
   */

  const para = (inner: string) =>
    `<!-- wp:paragraph -->\n<p>${inner}</p>\n<!-- /wp:paragraph -->\n\n`;

  it("nests a wp:image block comment inside the paragraph's p tag", () => {
    // An image is an inline token, so the Gutenberg block comment it renders to
    // lands between the <p> tags rather than beside them. Invalid Gutenberg,
    // and exactly what Python emits.
    expect(markdownToWpHtml("a ![x](/b.png) c\n")).toBe(
      para(
        "a <!-- wp:image -->\n" +
          '<figure class="wp-block-image"><img src="/b.png" alt="x"/></figure>\n' +
          "<!-- /wp:image -->\n\n c",
      ),
    );
  });

  it("counts an even backslash run before a bracket as an opening bracket", () => {
    // `_INLINE_SQUARE_BRACKET_RE` carries the backslash run into the match, and
    // mistune compares the whole match against "]", so `\\]` raises the nesting
    // level instead of lowering it. The text therefore runs to the *next* `]`.
    expect(markdownToWpHtml("[a\\\\](/b)\n")).toBe(
      para('<a href="/b">a\\</a>'),
    );
  });

  it("does not balance parentheses inside an href", () => {
    expect(markdownToWpHtml("[a](/b(c))\n")).toBe(
      para('<a href="/b(c">a</a>)'),
    );
  });

  it("drops an empty title rather than emitting the attribute", () => {
    expect(markdownToWpHtml('[a](/b "")\n')).toBe(para('<a href="/b">a</a>'));
  });

  it("keeps the first label for a collapsed reference and the second for a full one", () => {
    expect(markdownToWpHtml("[a][]\n\n[a]: /b\n")).toBe(
      para('<a href="/b">a</a>'),
    );
    expect(markdownToWpHtml("[text][a]\n\n[a]: /b\n")).toBe(
      para('<a href="/b">text</a>'),
    );
  });

  it("declines a reference whose label is not defined, leaving the source text", () => {
    expect(markdownToWpHtml("[a][b]\n\n[c]: /d\n")).toBe(para("[a][b]"));
  });

  it("cannot resolve a bracket counted text as a reference", () => {
    // `LINK_LABEL` admits no bare bracket, so both layers refuse: the block
    // rule never records the definition, and inline the nested bracket forces
    // `parse_link_text`, which produces a text but no label. Two paragraphs.
    expect(markdownToWpHtml("[a [b] c]\n\n[a [b] c]: /d\n")).toBe(
      para("[a [b] c]") + para("[a [b] c]: /d"),
    );
  });

  it("keeps a backslashed line separator inside a label", () => {
    // Python's `.` in LINK_LABEL is `[^\n]`. JavaScript's also refuses U+2028,
    // so spelling the class out is what lets both the definition and the
    // reference parse.
    expect(markdownToWpHtml("[a\\\u2028b]: /c\n\n[a\\\u2028b]\n")).toBe(
      para('<a href="/c">a\\\u2028b</a>'),
    );
  });

  it("nests an image inside a link text but not a link inside a link text", () => {
    expect(markdownToWpHtml("[a ![b](/c.png) d](/e)\n")).toContain("wp:image");
    expect(markdownToWpHtml("[a [b](/c) d](/e)\n")).toBe(
      para('<a href="/e">a [b](/c) d</a>'),
    );
  });

  it("nests a link inside an image alt but not an image inside an image alt", () => {
    expect(markdownToWpHtml("![a [b](/c) d](/e.png)\n")).toContain("<a href");
    expect(markdownToWpHtml("![a ![b](/c.png) d](/e.png)\n")).not.toContain(
      "<a href",
    );
  });

  it("gives up only the opening bracket when the rule declines", () => {
    // The scan loop restarts one character past the `[` it emitted as text, so
    // the second bracket still opens a link.
    expect(markdownToWpHtml("[[a](/b)\n")).toBe(para('[<a href="/b">a</a>'));
  });

  it("loses a link to a codespan that outruns it", () => {
    expect(markdownToWpHtml("[a `b](/c)` d](/e)\n")).toBe(
      para("[a <code>b](/c)</code> d](/e)"),
    );
  });

  it("interpolates a url and an alt without escaping either", () => {
    // Both are f-strings in Python, so a quote in the url breaks out of the
    // attribute. Pinned so a later fix is a deliberate divergence.
    expect(
      renderTokens([
        {
          type: "image",
          children: [{ type: "text", raw: 'a" b' }],
          attrs: { url: '/x" onerror="y' },
        },
      ]),
    ).toBe(
      "<!-- wp:image -->\n" +
        '<figure class="wp-block-image"><img src="/x" onerror="y" alt="a" b"/></figure>\n' +
        "<!-- /wp:image -->\n\n",
    );
  });

  it("resolves a definition written inside a quote or a list item", () => {
    // `BlockState.child_state` shares the env with its parent, so a definition
    // nested in another block is visible to the whole document.
    expect(markdownToWpHtml("> [a]: /b\n\n[a]\n")).toContain('<a href="/b">');
    expect(markdownToWpHtml("- [a]: /b\n\n[a]\n")).toContain('<a href="/b">');
  });
});
