import { describe, expect, it } from "vitest";

import parity from "./data/wp-html-inline-escape-codespan-parity.json";
import { UnportedMarkdownError, markdownToWpHtml } from "./wp-html";

/**
 * The inline `escape` and `codespan` rules, replayed against the real Python
 * function. `parity.cases` is generated by
 * `api/scripts/export_wp_html_inline_escape_codespan_parity.py`; nothing in this
 * file asserts an expectation that was written by hand except the negative
 * controls at the bottom, which were added after the replay passed.
 *
 * These are the two inline rules that need nothing from the inline state, so
 * this item ports the state and the scan loop alongside them. The export script
 * refuses to write a case whose paragraphs reach `emphasis`, `link`,
 * `auto_link`, `auto_email` or `inline_html`, so every case here is one the
 * TypeScript port is expected to render, not one pinned for later.
 */

type Case = { name: string; markdown: string; html: string };

const cases = parity.cases as Case[];

describe("markdownToWpHtml, the escape and codespan inline rules", () => {
  it("has an oracle generated from the Python implementation", () => {
    expect(parity.source).toBe(
      "api/src/services/wp_html.py::markdown_to_wp_html",
    );
    expect(cases.length).toBeGreaterThanOrEqual(85);
  });

  it.each(cases.map((c): [string, Case] => [c.name, c]))(
    "matches Python's HTML byte for byte: %s",
    (_name, testCase) => {
      expect(markdownToWpHtml(testCase.markdown)).toBe(testCase.html);
    },
  );
});

describe("hand written controls", () => {
  /**
   * Written after the replay passed, and every value here was checked against
   * the real Python function before being committed. They cover seams the
   * generated corpus reaches only indirectly.
   */

  const para = (inner: string) =>
    `<!-- wp:paragraph -->\n<p>${inner}</p>\n<!-- /wp:paragraph -->\n\n`;

  it("emits the escaped character without its backslash", () => {
    expect(markdownToWpHtml("\\*a\\*\n")).toBe(para("*a*"));
  });

  it("takes a run of escapes as one token", () => {
    expect(markdownToWpHtml("\\*\\_\\`\n")).toBe(para("*_`"));
  });

  it("leaves a backslash that does not precede punctuation alone", () => {
    expect(markdownToWpHtml("a \\x b\n")).toBe(para("a \\x b"));
  });

  it("lets an escaped backslash keep the following newline a soft break", () => {
    // `\\` is consumed by `escape`, so the newline is no longer preceded by a
    // backslash and `linebreak` cannot claim it.
    expect(markdownToWpHtml("a\\\\\nb\n")).toBe(para("a\\\nb"));
    expect(markdownToWpHtml("a\\\nb\n")).toBe(para("a<br />\nb"));
  });

  it("does not html escape the code it renders", () => {
    // `_GutenbergRenderer.codespan` interpolates `raw` directly, so a codespan
    // is the one place markdown can put a raw `&` or `<` into the output.
    expect(markdownToWpHtml("`a & b`\n")).toBe(para("<code>a & b</code>"));
    expect(markdownToWpHtml("`<div>`\n")).toBe(para("<code><div></code>"));
  });

  it("requires the closing run to be exactly as long as the opening one", () => {
    expect(markdownToWpHtml("``a`b``\n")).toBe(para("<code>a`b</code>"));
    expect(markdownToWpHtml("``a```\n")).toBe(para("``a```"));
  });

  it("leaves an unclosed marker as literal text", () => {
    expect(markdownToWpHtml("`code\n")).toBe(para("`code"));
    expect(markdownToWpHtml("``\n")).toBe(para("``"));
  });

  it("folds a newline inside a codespan into a space", () => {
    expect(markdownToWpHtml("`a\nb`\n")).toBe(para("<code>a b</code>"));
  });

  it("strips one space from each end only when both are present", () => {
    expect(markdownToWpHtml("` a `\n")).toBe(para("<code>a</code>"));
    expect(markdownToWpHtml("` a`\n")).toBe(para("<code> a</code>"));
    expect(markdownToWpHtml("`a `\n")).toBe(para("<code>a </code>"));
    expect(markdownToWpHtml("`  a  `\n")).toBe(para("<code> a </code>"));
  });

  it("keeps the spaces of an all whitespace codespan", () => {
    // `len(code.strip())` is 0, so the strip branch never runs.
    expect(markdownToWpHtml("`  `\n")).toBe(para("<code>  </code>"));
    expect(markdownToWpHtml("` `\n")).toBe(para("<code> </code>"));
  });

  it("gives a codespan precedence over an escape that starts later", () => {
    // The scan is leftmost first, so the backtick at index 0 wins and the
    // backslash escape inside the code is never parsed.
    expect(markdownToWpHtml("`a\\*b`\n")).toBe(para("<code>a\\*b</code>"));
    expect(markdownToWpHtml("\\`a`\n")).toBe(para("`a`"));
  });

  it("declines a backtick fence whose info string holds a backtick", () => {
    // The block rule refuses, the line falls back to a paragraph, and the
    // backticks it still holds are what this item renders.
    expect(markdownToWpHtml("```a`b\n")).toBe(para("```a`b"));
  });

  it("still stops on the inline rules that are not ported yet", () => {
    for (const [markdown, rule] of [
      ["*a*\n", "emphasis"],
      ["[a](/b)\n", "link"],
      ["<https://example.com>\n", "auto_link"],
      ["<a@example.com>\n", "auto_email"],
      ["a <span>b</span>\n", "inline_html"],
    ] as const) {
      let thrown: unknown;
      try {
        markdownToWpHtml(markdown);
      } catch (error) {
        thrown = error;
      }
      expect(thrown).toBeInstanceOf(UnportedMarkdownError);
      expect((thrown as UnportedMarkdownError).rule).toBe(rule);
    }
  });
});
