import { describe, expect, it } from "vitest";

import parity from "./data/wp-html-inline-autolink-parity.json";
import {
  MissingRendererError,
  markdownToWpHtml,
  parseInlineTokens,
  renderTokens,
  type Token,
} from "./wp-html";

/**
 * The inline `auto_link`, `auto_email` and `inline_html` rules, replayed
 * against the real Python implementation. Every expectation in
 * `data/wp-html-inline-autolink-parity.json` is generated by
 * `api/scripts/export_wp_html_inline_autolink_parity.py`; nothing in this file
 * asserts a value written by hand except the negative controls at the bottom,
 * which were added after the replay passed.
 *
 * Three corpora, because these rules cannot all be observed the same way:
 *
 * * `html_cases` are whole documents. An autolink case pins the HTML, and an
 *   `inline_html` case pins the `AttributeError` mistune raises because
 *   `_GutenbergRenderer` has no method for that token.
 * * `token_cases` are single inline strings run through mistune's own
 *   `InlineParser.__call__`. This is the only surface the `in_link` flag is
 *   visible on, since the rule that toggles it is also the rule that aborts
 *   rendering.
 * * `render_cases` are single `link` tokens run through
 *   `_GutenbergRenderer.link`, which is how the title branch of that method is
 *   pinned before the `link` rule exists to build a token carrying one.
 */

type HtmlCase = {
  name: string;
  markdown: string;
  html?: string;
  error?: { type: string; message: string };
};
type TokenCase = { name: string; src: string; tokens: Token[] };
type RenderCase = { name: string; token: Token; html: string };

const htmlCases = parity.html_cases as HtmlCase[];
const tokenCases = parity.token_cases as TokenCase[];
const renderCases = parity.render_cases as RenderCase[];

describe("markdownToWpHtml, the autolink and inline html rules", () => {
  it("has an oracle generated from the Python implementation", () => {
    expect(parity.source).toBe(
      "api/src/services/wp_html.py::markdown_to_wp_html",
    );
    expect(parity.token_source).toBe("mistune.InlineParser.__call__");
    expect(htmlCases.length).toBeGreaterThanOrEqual(75);
    expect(tokenCases.length).toBeGreaterThanOrEqual(15);
    expect(renderCases.length).toBeGreaterThanOrEqual(6);
    // Both outcomes have to be represented or the corpus proves only one half.
    expect(htmlCases.filter((c) => c.error).length).toBeGreaterThanOrEqual(10);
    expect(htmlCases.filter((c) => c.html).length).toBeGreaterThanOrEqual(60);
  });

  it.each(htmlCases.map((c): [string, HtmlCase] => [c.name, c]))(
    "matches Python's HTML byte for byte: %s",
    (_name, testCase) => {
      if (testCase.error) {
        // Python's `BaseRenderer._get_method` raises
        // `AttributeError: No renderer "'inline_html'"`.
        expect(testCase.error.type).toBe("AttributeError");
        expect(testCase.error.message).toBe("No renderer \"'inline_html'\"");
        try {
          markdownToWpHtml(testCase.markdown);
          throw new Error("expected markdownToWpHtml to throw");
        } catch (err) {
          expect(err).toBeInstanceOf(MissingRendererError);
          expect((err as MissingRendererError).tokenType).toBe("inline_html");
        }
        return;
      }
      expect(markdownToWpHtml(testCase.markdown)).toBe(testCase.html);
    },
  );

  it.each(tokenCases.map((c): [string, TokenCase] => [c.name, c]))(
    "matches mistune's inline token stream: %s",
    (_name, testCase) => {
      expect(parseInlineTokens(testCase.src)).toEqual(testCase.tokens);
    },
  );

  it.each(renderCases.map((c): [string, RenderCase] => [c.name, c]))(
    "matches the Python link renderer: %s",
    (_name, testCase) => {
      expect(renderTokens([testCase.token])).toBe(testCase.html);
    },
  );
});

describe("hand written controls", () => {
  /**
   * Written after the replay passed, and every value here was checked against
   * the real Python function before being committed. They cover seams the
   * generated corpora reach only indirectly.
   */

  const para = (inner: string) =>
    `<!-- wp:paragraph -->\n<p>${inner}</p>\n<!-- /wp:paragraph -->\n\n`;

  it("uses the bracketed text as both href and label", () => {
    expect(markdownToWpHtml("<https://example.com>\n")).toBe(
      para('<a href="https://example.com">https://example.com</a>'),
    );
  });

  it("escapes the href but not the label", () => {
    // `escape_url` percent encodes the href; the label keeps the raw bytes.
    expect(markdownToWpHtml("<https://example.com/café>\n")).toBe(
      para(
        '<a href="https://example.com/caf%C3%A9">https://example.com/café</a>',
      ),
    );
  });

  it("unescapes html entities in the href before percent encoding it", () => {
    // `escape_url` is `quote(unescape(link))`, so `&amp;` collapses to `&` in
    // the href while the label keeps the entity it was written with.
    expect(markdownToWpHtml("<https://e.example/?a=1&amp;b=2>\n")).toBe(
      para(
        '<a href="https://e.example/?a=1&b=2">https://e.example/?a=1&amp;b=2</a>',
      ),
    );
  });

  it("gives an email a mailto href the label never shows", () => {
    expect(markdownToWpHtml("<user@example.com>\n")).toBe(
      para('<a href="mailto:user@example.com">user@example.com</a>'),
    );
  });

  it("lets auto_link win over auto_email at the same offset", () => {
    // Rule order in the alternation is what breaks the tie, so a `mailto:`
    // address is an autolink and its label keeps the scheme.
    expect(markdownToWpHtml("<mailto:a@example.com>\n")).toBe(
      para('<a href="mailto:a@example.com">mailto:a@example.com</a>'),
    );
  });

  it("requires at least two characters before the scheme colon", () => {
    expect(markdownToWpHtml("<ab:x>\n")).toBe(para('<a href="ab:x">ab:x</a>'));
    // `_GutenbergRenderer.text` returns `raw`, so a string that fails every
    // inline rule reaches the paragraph with its angle brackets unescaped.
    expect(markdownToWpHtml("<a:x>\n")).toBe(para("<a:x>"));
  });

  it("caps the scheme at thirty two characters", () => {
    const long = "a".repeat(32);
    expect(markdownToWpHtml(`<${long}://x>\n`)).toBe(
      para(`<a href="${long}://x">${long}://x</a>`),
    );
    expect(markdownToWpHtml(`<${"a".repeat(33)}://x>\n`)).toBe(
      para(`<${"a".repeat(33)}://x>`),
    );
  });

  it("stops the autolink at the first space", () => {
    expect(markdownToWpHtml("<https://example.com/a b>\n")).toBe(
      para("<https://example.com/a b>"),
    );
  });

  it("turns in_link on for an anchor and back off for its close tag", () => {
    // The renderer aborts on the tag itself, so the flag is only visible in the
    // token stream: inside the anchor the autolink is text, after it a link.
    expect(parseInlineTokens('<a href="/x"><https://e.example>')).toEqual([
      { type: "inline_html", raw: '<a href="/x">' },
      { type: "text", raw: "<https://e.example>" },
    ]);
    expect(parseInlineTokens('<a href="/x"></a><https://e.example>')).toEqual([
      { type: "inline_html", raw: '<a href="/x">' },
      { type: "inline_html", raw: "</a>" },
      {
        type: "link",
        children: [{ type: "text", raw: "https://e.example" }],
        attrs: { url: "https://e.example" },
      },
    ]);
  });

  it("matches the four literal prefixes rather than parsing the tag", () => {
    // Python is `html.startswith(("<a ", "<a>", "<A ", "<A>"))`, so a tag whose
    // name is followed by a newline is a valid anchor that toggles nothing.
    expect(parseInlineTokens("<a\n><https://e.example>")[1]).toEqual({
      type: "link",
      children: [{ type: "text", raw: "https://e.example" }],
      attrs: { url: "https://e.example" },
    });
    expect(parseInlineTokens("<a><https://e.example>")[1]).toEqual({
      type: "text",
      raw: "<https://e.example>",
    });
  });

  it("does not toggle in_link for a tag that is not an anchor", () => {
    expect(parseInlineTokens("<b><https://e.example>")[1]).toEqual({
      type: "link",
      children: [{ type: "text", raw: "https://e.example" }],
      attrs: { url: "https://e.example" },
    });
  });

  it("interpolates the href and title into the anchor unescaped", () => {
    // `_GutenbergRenderer.link` uses an f-string, so a quote in either attribute
    // breaks out of it. Pinned so a later "improvement" that escapes them is a
    // deliberate divergence rather than a silent one.
    expect(
      renderTokens([
        {
          type: "link",
          children: [{ type: "text", raw: "a" }],
          attrs: { url: 'x"y', title: 'a"b' },
        },
      ]),
    ).toBe(`<a href="x"y" title="a"b">a</a>`);
  });

  it("omits the title attribute when the title is empty or null", () => {
    for (const title of [null, ""] as const) {
      expect(
        renderTokens([
          {
            type: "link",
            children: [{ type: "text", raw: "a" }],
            attrs: { url: "u", title },
          },
        ]),
      ).toBe('<a href="u">a</a>');
    }
  });

  it("renders a link now that -iii-d has ported the last inline rule", () => {
    expect(markdownToWpHtml("[a](/b)\n")).toBe(
      '<!-- wp:paragraph -->\n<p><a href="/b">a</a></p>\n' +
        "<!-- /wp:paragraph -->\n\n",
    );
  });
});
