import { describe, expect, it } from "vitest";

import parity from "./data/wp-html-block-parity.json";
import { UnportedMarkdownError, markdownToWpHtml } from "./wp-html";

/**
 * `markdown_to_wp_html`'s block half, replayed against the real Python
 * function's output. `parity.cases` is generated by
 * `api/scripts/export_wp_html_block_parity.py`; nothing in this file asserts an
 * expectation that was written by hand, because the whole risk in this port is
 * that a JavaScript markdown parser and mistune disagree about tokenisation in
 * ways that look reasonable from either side.
 */

type Case = { name: string; markdown: string; html: string };
const cases = parity.cases as Case[];

describe("markdownToWpHtml, block level", () => {
  it("has an oracle generated from the Python implementation", () => {
    expect(parity.source).toBe(
      "api/src/services/wp_html.py::markdown_to_wp_html",
    );
    expect(cases.length).toBeGreaterThanOrEqual(70);
  });

  it.each(cases.map((c): [string, Case] => [c.name, c]))(
    "matches Python byte for byte: %s",
    (_name, testCase) => {
      expect(markdownToWpHtml(testCase.markdown)).toBe(testCase.html);
    },
  );
});

describe("the oracle has teeth", () => {
  /**
   * Negative controls. Each is a plausible way to get the port wrong that the
   * replay above would catch, asserted here so the corpus is not merely a set
   * of cases that any markdown library would pass.
   */

  it("does not treat a run of dashes under a paragraph as a separator", () => {
    // The tokenizer rewrites the paragraph above into a setext heading, which
    // a renderer-only port that mapped `---` straight to <hr> would miss.
    expect(markdownToWpHtml("Para.\n--\n")).toContain("<h2>Para.</h2>");
    expect(markdownToWpHtml("Para.\n--\n")).not.toContain("wp:separator");
  });

  it("keeps the same dashes a separator when nothing precedes them", () => {
    expect(markdownToWpHtml("---\n")).toContain("wp:separator");
  });

  it("omits the level attribute for h2 only", () => {
    expect(markdownToWpHtml("## T\n")).toContain("<!-- wp:heading -->");
    expect(markdownToWpHtml("# T\n")).toContain('<!-- wp:heading {"level":1} -->');
    expect(markdownToWpHtml("### T\n")).toContain('<!-- wp:heading {"level":3} -->');
  });

  it("does not escape HTML metacharacters, in prose or in code", () => {
    // The renderer's `text` returns the raw token, so `&` stays `&`. A port
    // built on a library whose default renderer escapes would produce
    // `&amp;` and publish visibly wrong copy.
    expect(markdownToWpHtml("Tom & Jerry\n")).toContain("<p>Tom & Jerry</p>");
    expect(markdownToWpHtml("```\n<b>&</b>\n```\n")).toContain("<code><b>&</b>\n</code>");
  });

  it("strips leading indentation from the document before parsing", () => {
    // `.strip()` runs first, so four leading spaces at the top of a document
    // are not an indented code block.
    expect(markdownToWpHtml("    code line\n")).toContain("<p>code line</p>");
    expect(markdownToWpHtml("Para.\n\n    code line\n")).toContain(
      "<pre class=\"wp-block-code\"><code>code line</code></pre>",
    );
  });

  it("keeps the trailing newline of a fenced block and drops it from an indented one", () => {
    expect(markdownToWpHtml("```\na\n```\n")).toContain("<code>a\n</code>");
    expect(markdownToWpHtml("P.\n\n    a\n")).toContain("<code>a</code>");
  });

  it("refuses a fence whose backtick info string holds a backtick", () => {
    // The decline sends the line to the paragraph fallback, so the backticks
    // reach the inline parser. An accepted fence would never get there, which
    // is what makes the throw the assertion. (The rendered form of this input
    // belongs to the b-iii corpus, since a codespan is what comes out.)
    expect(() => markdownToWpHtml("```a`b\nx\n```\n")).toThrowError(
      UnportedMarkdownError,
    );
    expect(() => markdownToWpHtml("```ab\nx\n```\n")).not.toThrow();
  });

  it("distinguishes a soft break from a hard one", () => {
    expect(markdownToWpHtml("a\nb\n")).toContain("<p>a\nb</p>");
    expect(markdownToWpHtml("a  \nb\n")).toContain("<p>a<br />\nb</p>");
  });

  it("closes an unclosed fence at the end of the document", () => {
    expect(markdownToWpHtml("```py\nx\n")).toBe(
      '<!-- wp:code {"language":"py"} -->\n' +
        '<pre class="wp-block-code"><code>x\n</code></pre>\n' +
        "<!-- /wp:code -->\n\n",
    );
  });
});

describe("constructs whose handlers are not ported yet", () => {
  /**
   * These throw rather than falling through to a paragraph, so that wiring the
   * converter into the publish workflow before 5.3c-iii-b-1-b-iii lands cannot
   * silently drop a link.
   *
   * Only inline rules are left. `block_quote` was listed here until
   * 5.3c-iii-b-1-b-ii-1 ported it, `list` until -ii-2, `raw_html` until -ii-3-a
   * and `ref_link` until -ii-3-b-2, which finished the block layer; their
   * coverage is now `wp-html-quotes.test.ts`, `wp-html-lists.test.ts`,
   * `wp-html-raw-html.test.ts` and `wp-html-ref-link.test.ts`.
   */

  it.each([
    ["emphasis", "an *emphasised* word\n"],
    ["codespan", "an `inline code` word\n"],
    ["link", "a [link](https://example.com) here\n"],
    ["escape", "a \\* literal asterisk\n"],
    ["auto_link", "an <https://example.com> autolink\n"],
  ])("throws for the %s inline rule", (rule, markdown) => {
    expect(() => markdownToWpHtml(markdown)).toThrowError(UnportedMarkdownError);
    try {
      markdownToWpHtml(markdown);
    } catch (error) {
      expect((error as UnportedMarkdownError).rule).toBe(rule);
      expect((error as Error).message).toContain("5.3c-iii-b-1-b-iii");
    }
  });
});
