import { describe, expect, it } from "vitest";

import parity from "./data/wp-html-inline-emphasis-parity.json";
import {
  MissingRendererError,
  markdownToWpHtml,
  parseInlineTokens,
  renderTokens,
  type Token,
} from "./wp-html";

/**
 * The inline `emphasis` rule, the `emphasis` and `strong` renderer methods and
 * `precedence_scan`, replayed against the real Python implementation. Every
 * expectation in `data/wp-html-inline-emphasis-parity.json` is generated by
 * `api/scripts/export_wp_html_inline_emphasis_parity.py`; nothing here asserts a
 * value written by hand except the negative controls at the bottom, which were
 * added after the replay passed.
 *
 * Three corpora again, for the same reasons the autolink item needed three:
 *
 * * `html_cases` are whole documents, and the two that win a precedence scan
 *   with a tag pin the `AttributeError` rather than an HTML string.
 * * `token_cases` are single inline strings through mistune's own
 *   `InlineParser.__call__`. The rendered HTML flattens the `emphasis` wrapping
 *   the `strong` that a triple marker builds, so the nesting is only visible in
 *   the token stream.
 * * `render_cases` are single tokens through `_GutenbergRenderer.emphasis` and
 *   `.strong`, which is how the empty-children branch is pinned.
 */

type HtmlCase = {
  name: string;
  markdown: string;
  html?: string;
  error?: { type: string; message: string };
};
type TokenCase = { name: string; src: string; tokens: Token[] };
type RenderCase = { name: string; method: string; token: Token; html: string };

const htmlCases = parity.html_cases as HtmlCase[];
const tokenCases = parity.token_cases as TokenCase[];
const renderCases = parity.render_cases as RenderCase[];

describe("markdownToWpHtml, the emphasis rule and the precedence scan", () => {
  it("has an oracle generated from the Python implementation", () => {
    expect(parity.source).toBe(
      "api/src/services/wp_html.py::markdown_to_wp_html",
    );
    expect(parity.token_source).toBe("mistune.InlineParser.__call__");
    expect(htmlCases.length).toBeGreaterThanOrEqual(65);
    expect(tokenCases.length).toBeGreaterThanOrEqual(12);
    expect(renderCases.length).toBeGreaterThanOrEqual(6);
    // Both outcomes have to be represented or the corpus proves only one half.
    expect(htmlCases.filter((c) => c.error).length).toBeGreaterThanOrEqual(2);
    expect(htmlCases.filter((c) => c.html).length).toBeGreaterThanOrEqual(60);
  });

  it.each(htmlCases.map((c): [string, HtmlCase] => [c.name, c]))(
    "matches Python's HTML byte for byte: %s",
    (_name, testCase) => {
      if (testCase.error) {
        // Python's `BaseRenderer._get_method` raises
        // `AttributeError: No renderer "'inline_html'"`.
        expect(testCase.error.type).toBe("AttributeError");
        expect(testCase.error.message).toBe("No renderer \"'inline_html'\"");
        try {
          markdownToWpHtml(testCase.markdown);
          expect.unreachable("expected a MissingRendererError");
        } catch (error) {
          expect(error).toBeInstanceOf(MissingRendererError);
          expect((error as MissingRendererError).tokenType).toBe("inline_html");
        }
        return;
      }
      expect(markdownToWpHtml(testCase.markdown)).toBe(testCase.html);
    },
  );

  it.each(tokenCases.map((c): [string, TokenCase] => [c.name, c]))(
    "matches mistune's inline token stream: %s",
    (_name, testCase) => {
      expect(parseInlineTokens(testCase.src)).toEqual(testCase.tokens);
    },
  );

  it.each(renderCases.map((c): [string, RenderCase] => [c.name, c]))(
    "matches the Python renderer method: %s",
    (_name, testCase) => {
      expect(renderTokens([testCase.token])).toBe(testCase.html);
    },
  );
});

/**
 * Controls written after the replay passed. Each one names a behaviour the
 * corpus depends on but does not label, so a later change that breaks it fails
 * with a readable reason instead of a diff on case 43.
 */
describe("emphasis behaviours the corpus depends on", () => {
  const body = (html: string) =>
    html
      .replace("<!-- wp:paragraph -->\n<p>", "")
      .replace(/<\/p>\n[\s\S]*$/, "");

  it("emits a strong nested inside an emphasis for a triple marker", () => {
    expect(parseInlineTokens("***a***")).toEqual([
      {
        type: "emphasis",
        children: [{ type: "strong", children: [{ type: "text", raw: "a" }] }],
      },
    ]);
  });

  it("treats a repeated single marker inside an emphasis as text", () => {
    // The closer is the first `*` the end pattern finds, which is the one that
    // reads as the inner opener, so the run is `a *b` and the tail stays.
    expect(body(markdownToWpHtml("*a *b* c*\n"))).toBe("<em>a *b</em> c*");
  });

  it("still opens a strong inside an emphasis", () => {
    expect(body(markdownToWpHtml("*a **b** c*\n"))).toBe(
      "<em>a <strong>b</strong> c</em>",
    );
  });

  it("uses Python's Unicode word boundary before an opening underscore", () => {
    // `é` is a word character to Python and not to JavaScript's `\b`, so an
    // ASCII boundary would open an emphasis here and Python does not.
    expect(body(markdownToWpHtml("café_a_\n"))).toBe("café_a_");
    // A combining mark is not a word character either way.
    expect(body(markdownToWpHtml("á_b_\n"))).toBe("á<em>b</em>");
  });

  it("uses Python's Unicode word boundary after a closing underscore", () => {
    expect(body(markdownToWpHtml("_a_é\n"))).toBe("_a_é");
    expect(body(markdownToWpHtml("_a_.\n"))).toBe("<em>a</em>.");
  });

  it("gives a codespan that outruns the emphasis the whole run", () => {
    expect(body(markdownToWpHtml("*a `b* c` d*\n"))).toBe(
      "*a <code>b* c</code> d*",
    );
  });

  it("keeps the emphasis when the codespan ends before the closer", () => {
    expect(body(markdownToWpHtml("*a `b` c*\n"))).toBe(
      "<em>a <code>b</code> c</em>",
    );
  });

  it("keeps the emphasis when the codespan never closes", () => {
    expect(body(markdownToWpHtml("*a `b* c\n"))).toBe("<em>a `b</em> c");
  });

  it("gives an autolink that outruns the emphasis the whole run", () => {
    expect(body(markdownToWpHtml("*a <https://example.com/*b> c*\n"))).toBe(
      '*a <a href="https://example.com/*b">https://example.com/*b</a> c*',
    );
  });

  it("does not close on a marker preceded by whitespace", () => {
    expect(body(markdownToWpHtml("*a *\n"))).toBe("*a *");
  });

  it("closes on the backslash of an escape rather than skipping it", () => {
    // `[^\s*]` matches the backslash itself, so the escape alternative in the
    // end pattern almost never wins: `\*` closes the run at the backslash and
    // the `*` is consumed as the marker.
    expect(body(markdownToWpHtml("*a\\*b*\n"))).toBe("<em>a\\</em>b*");
  });

  it("re-parses the closed run, so an escape inside it still unescapes", () => {
    expect(body(markdownToWpHtml("*\\**\n"))).toBe("<em>*</em>");
    expect(body(markdownToWpHtml("*a\\\\* b\n"))).toBe("<em>a\\</em> b");
  });

  it("uses Python's whitespace set on both sides of the marker", () => {
    // `\x1c` is whitespace to Python and not to JavaScript; `\ufeff` is the
    // other way round. Both sides of the rule read the class, so all four
    // combinations differ from the JavaScript `\s` spelling.
    expect(body(markdownToWpHtml("a *\x1cb* c\n"))).toBe("a *\x1cb* c");
    expect(body(markdownToWpHtml("a *\ufeffb* c\n"))).toBe(
      "a <em>\ufeffb</em> c",
    );
    expect(body(markdownToWpHtml("*a\x1c*\n"))).toBe("*a\x1c*");
    expect(body(markdownToWpHtml("*a\ufeff*\n"))).toBe("<em>a\ufeff</em>");
  });

  it("does not open on a marker followed by whitespace", () => {
    // `* a*` would be a list bullet, so the control uses the markers that stay
    // inside the paragraph.
    expect(body(markdownToWpHtml("_ a_\n"))).toBe("_ a_");
    expect(body(markdownToWpHtml("** a**\n"))).toBe("** a**");
  });
});
