import { describe, expect, it } from "vitest";

import parity from "./data/wp-html-ref-link-parity.json";
import {
  MissingRendererError,
  markdownToWpHtml,
  parseRefLinks,
} from "./wp-html";

/**
 * `markdown_to_wp_html`'s `ref_link` rule, replayed against the real Python
 * function. `parity.cases` is generated by
 * `api/scripts/export_wp_html_ref_link_parity.py`; nothing in this file asserts
 * an expectation that was written by hand except the negative controls at the
 * bottom, which were added after the replay passed.
 *
 * Two channels, because one is not enough. The rendered HTML only shows whether
 * the definition line was consumed, since `_GutenbergRenderer` never reads
 * `state.env`; the definition itself is asserted through `parseRefLinks`, which
 * stops after the block parse exactly where Python fills the env.
 */

type RefLink = { url: string; label: string; title?: string };
type Case = {
  name: string;
  markdown: string;
  ref_links: Record<string, RefLink>;
  html: string;
};
type Decline = {
  name: string;
  markdown: string;
  ref_links: Record<string, RefLink>;
  python_html: string | null;
};

const cases = parity.cases as Case[];
const declines = parity.declines as Decline[];

describe("markdownToWpHtml, reference link definitions", () => {
  it("has an oracle generated from the Python implementation", () => {
    expect(parity.source).toBe(
      "api/src/services/wp_html.py::markdown_to_wp_html",
    );
    expect(cases.length).toBeGreaterThanOrEqual(90);
  });

  it.each(cases.map((c): [string, Case] => [c.name, c]))(
    "matches Python's HTML byte for byte: %s",
    (_name, testCase) => {
      expect(markdownToWpHtml(testCase.markdown)).toBe(testCase.html);
    },
  );

  it.each(cases.map((c): [string, Case] => [c.name, c]))(
    "matches Python's ref_links exactly: %s",
    (_name, testCase) => {
      expect(parseRefLinks(testCase.markdown)).toEqual(testCase.ref_links);
    },
  );
});

describe("definitions the rule refuses", () => {
  /**
   * A refused definition leaves its line to the paragraph fallback, and that
   * paragraph holds a `[`, which fires the inline `link` rule. That rule threw
   * until ledger item 5.3c-iii-b-1-b-iii-d ported it, so the oracle carries
   * `python_html` rather than `html`; it is now compared, alongside the
   * `ref_links` this item ports, which every one of these must leave untouched
   * by the definition it refused. One case leaves a tag in the paragraph, and
   * `_GutenbergRenderer` has no `inline_html` method, so it raises instead.
   */

  it("covers every way a definition can be refused", () => {
    expect(declines.length).toBeGreaterThanOrEqual(20);
  });

  it.each(declines.map((d): [string, Decline] => [d.name, d]))(
    "leaves ref_links matching Python: %s",
    (_name, decline) => {
      expect(parseRefLinks(decline.markdown)).toEqual(decline.ref_links);
    },
  );

  it.each(declines.map((d): [string, Decline] => [d.name, d]))(
    "falls through to the paragraph Python rendered: %s",
    (_name, decline) => {
      if (decline.python_html === null) {
        expect(() => markdownToWpHtml(decline.markdown)).toThrowError(
          MissingRendererError,
        );
        return;
      }
      expect(markdownToWpHtml(decline.markdown)).toBe(decline.python_html);
    },
  );
});

describe("hand written controls", () => {
  /**
   * Written after the replay passed, and every value here was checked against
   * the real Python function before being committed. They cover seams the
   * generated corpus reaches only indirectly.
   */

  it("keys the map with `has`, not the prototype chain", () => {
    // `unikey` upper-cases, so no label can reach `Object.prototype`. Pinned so
    // a future folding change cannot quietly reintroduce the hazard.
    expect(parseRefLinks("[constructor]: /url\n")).toEqual({
      CONSTRUCTOR: { url: "/url", label: "constructor" },
    });
    expect(Object.keys(parseRefLinks("[constructor]: /url\n"))).toEqual([
      "CONSTRUCTOR",
    ]);
  });

  it("shares the env between a block quote and the document", () => {
    expect(parseRefLinks("> [a]: /inside\n\n[b]: /outside\n")).toEqual({
      A: { url: "/inside", label: "a" },
      B: { url: "/outside", label: "b" },
    });
  });

  it("runs the href through escape_url, not encodeURI", () => {
    // `&amp;` unescapes to `&`, which is in escape_url's safe set and survives
    // literally; `&lt;` unescapes to `<`, which is not, and is percent encoded.
    expect(parseRefLinks("[a]: /x?u=&amp;v=&lt;\n").A.url).toBe("/x?u=&v=%3C");
  });

  it("unescapes backslash escapes in the href before encoding it", () => {
    expect(parseRefLinks("[a]: /url\\_x\n").A.url).toBe("/url_x");
  });

  it("keeps a backslash that does not precede punctuation", () => {
    expect(parseRefLinks("[a]: /url\\x\n").A.url).toBe("/url%5Cx");
  });

  it("drops an empty title but keeps the definition", () => {
    expect(parseRefLinks('[a]: /url ""\n')).toEqual({
      A: { url: "/url", label: "a" },
    });
  });

  it("stores the raw label, not the folded key", () => {
    expect(parseRefLinks("[  Foo   Bar  ]: /url\n")).toEqual({
      "FOO BAR": { url: "/url", label: "  Foo   Bar  " },
    });
  });

  it("refuses a definition whose href is followed by anything but a newline", () => {
    expect(parseRefLinks("[a]: /url x\n")).toEqual({});
  });

  it("stops the title scan at the blank line that ends the definition", () => {
    expect(parseRefLinks('[a]: /url\n\n"title"\n')).toEqual({
      A: { url: "/url", label: "a" },
    });
  });

  it("accepts a title on the line after the href", () => {
    expect(parseRefLinks('[a]: /url\n"title"\n')).toEqual({
      A: { url: "/url", label: "a", title: "title" },
    });
  });

  it("refuses an angle bracket href holding a backslash", () => {
    expect(parseRefLinks("[a]: <a\\b>\n")).toEqual({});
  });

  it("accepts an empty angle bracket href", () => {
    expect(parseRefLinks("[a]: <>\n")).toEqual({ A: { url: "", label: "a" } });
  });

  it("consumes the definition without emitting a token", () => {
    expect(markdownToWpHtml("[a]: /url\n\nPara.\n")).toBe(
      "<!-- wp:paragraph -->\n<p>Para.</p>\n<!-- /wp:paragraph -->\n\n",
    );
  });
});
