// @vitest-environment node
/**
 * `POST /api/posts`: the profile-driven prefill and the auto-enqueue that
 * replaces ARQ's `enqueue_job("run_pipeline_stage", post.id)`.
 *
 * Two layers. The first replays `create-parity.json`, generated by driving the
 * real `create_post` coroutine on the Python interpreter over ten bodies and
 * profiles, and asserts the ported prefill produces the same row for each. The
 * second runs the handler against the real database with real BetterAuth
 * sessions and reads the `workflow.start` event back off the real Redis Streams
 * bus, so "the pipeline was started" is asserted from the transport rather than
 * from a spy.
 *
 * Fixture profiles gate `research` at "review" on purpose. No worker runs in
 * this file, but other test files start workers on the shared Mastra instance,
 * and a run of this workflow they pick up would otherwise reach a provider. A
 * gated run suspends before it spends anything.
 *
 * Requires `docker compose up -d db redis`.
 */
import { RedisStreamsPubSub } from "@mastra/redis-streams"
import { eq, like } from "drizzle-orm"
import { afterAll, afterEach, beforeAll, describe, expect, it, vi } from "vitest"

import { closeDb, getDb, posts, websiteProfiles } from "@/db"
import { logger } from "@/mastra"
import { STAGES, STATUS_RUNNING } from "@/mastra/state"
import { apiRequest, createTestSession, deleteTestSessions, type TestSession } from "@/test/session"

import parity from "./data/create-parity.json"
import { applyProfilePrefill } from "./prefill"
import { GET as getPost } from "./[id]/route"
import { POST as createPost } from "./route"
import { POST_CREATE_DEFAULTS, postCreateSchema, type PostWriteInput } from "./validation"

/**
 * The one branch that cannot be driven from a real boundary is Python's queue
 * being unreachable, so `throw` exists for that. `skip` exists for the single
 * case whose body leaves `stage_settings` at the all-"auto" default: that run
 * has no review gate to stop it, and a worker started by another test file
 * would take it all the way to a provider. Every other test calls the real
 * implementation and asserts the event it published.
 */
const start = vi.hoisted(() => ({ mode: "real" as "real" | "throw" | "skip" }))

vi.mock("@/mastra/start-pipeline", async (importOriginal) => {
  const actual = await importOriginal<typeof import("@/mastra/start-pipeline")>()
  return {
    startPipeline: async (postId: string) => {
      if (start.mode === "throw") throw new Error("redis is down")
      if (start.mode === "skip") return "not-started"
      return actual.startPipeline(postId)
    },
  }
})

const PREFIX = "posts-create-test-"
const URL_BASE = "http://test/api/posts"

/** Discard port on loopback: nothing here should ever reach a real site. */
const SITE = "http://127.0.0.1:9/site"

/** `stage_settings` that pause the run at its first stage. */
const GATED_STAGE_SETTINGS = {
  research: "review",
  outline: "auto",
  write: "auto",
  edit: "auto",
  images: "auto",
  ready: "auto",
}

type StartEvent = { type: string; data?: { workflowId?: string; prevResult?: { output?: unknown } } }

const db = getDb()
const observer = new RedisStreamsPubSub({ url: process.env.REDIS_URL! })
const started: StartEvent[] = []

let user: TestSession
let other: TestSession

async function clearFixtures() {
  await db.delete(posts).where(like(posts.slug, `${PREFIX}%`))
  await db.delete(websiteProfiles).where(like(websiteProfiles.userId, `${PREFIX}%`))
}

async function insertProfile(
  userId: string,
  values: Partial<typeof websiteProfiles.$inferInsert> = {},
) {
  const [row] = await db
    .insert(websiteProfiles)
    .values({
      userId,
      name: "Test Blog",
      websiteUrl: SITE,
      defaultStageSettings: GATED_STAGE_SETTINGS,
      ...values,
    })
    .returning()
  return row
}

function create(body: unknown, cookie?: string) {
  return createPost(
    apiRequest(URL_BASE, {
      method: "POST",
      cookie,
      body: typeof body === "string" ? body : JSON.stringify(body),
    }),
  )
}

/** Resolves once a `workflow.start` for `pipeline` carrying `postId` arrives. */
async function waitForStart(postId: string, timeoutMs = 15_000): Promise<StartEvent> {
  const deadline = Date.now() + timeoutMs
  for (;;) {
    const match = started.find(
      (event) =>
        event.data?.workflowId === "pipeline" &&
        (event.data?.prevResult?.output as { postId?: string } | undefined)?.postId === postId,
    )
    if (match) return match
    if (Date.now() > deadline) {
      throw new Error(`no workflow.start for ${postId} within ${timeoutMs}ms`)
    }
    await new Promise((resolve) => setTimeout(resolve, 25))
  }
}

beforeAll(async () => {
  // No `group`, so this subscription is its own fan-out consumer group and can
  // never take an event away from a worker.
  await observer.subscribe("workflows", (event: unknown) => {
    started.push(event as StartEvent)
  })
  await clearFixtures()
  await deleteTestSessions(PREFIX)
  user = await createTestSession(PREFIX)
  other = await createTestSession(PREFIX)
})

afterEach(async () => {
  start.mode = "real"
  started.length = 0
  await clearFixtures()
})

afterAll(async () => {
  await clearFixtures()
  await deleteTestSessions(PREFIX)
  await observer.close()
  await closeDb()
})

// --- Parity against the Python endpoint -------------------------------------

/** A recorded profile turned into the row shape `applyProfilePrefill` reads. */
function profileRow(recorded: Record<string, unknown>): typeof websiteProfiles.$inferSelect {
  return {
    niche: recorded.niche,
    targetAudience: recorded.target_audience,
    tone: recorded.tone,
    brandVoice: recorded.brand_voice,
    wordCount: recorded.word_count,
    outputFormat: recorded.output_format,
    websiteUrl: recorded.website_url,
    imageStyle: recorded.image_style,
    imageBrandColors: recorded.image_brand_colors,
    imageExclude: recorded.image_exclude,
    avoid: recorded.avoid,
    requiredMentions: recorded.required_mentions,
    relatedKeywords: recorded.related_keywords,
    defaultStageSettings: recorded.default_stage_settings,
    wpDefaultCategoryId: recorded.wp_default_category_id,
    wpDefaultAuthorId: recorded.wp_default_author_id,
  } as unknown as typeof websiteProfiles.$inferSelect
}

describe("create_post parity", () => {
  it("was generated against the endpoint this port replaces", () => {
    expect(parity.source).toContain("create_post")
    expect(parity.cases).toHaveLength(10)
  })

  it("carries the same schema defaults pydantic dumped", () => {
    const [minimal] = parity.cases
    const recorded = { ...(minimal.post as Record<string, unknown>) }
    delete recorded.current_stage
    delete recorded.stage_status
    expect({ ...POST_CREATE_DEFAULTS, slug: minimal.body.slug, topic: minimal.body.topic }).toEqual(
      recorded,
    )
  })

  for (const [index, testCase] of parity.cases.entries()) {
    it(`case ${index + 1}: ${testCase.name}`, () => {
      const parsed = postCreateSchema.safeParse(testCase.body)
      expect(parsed.success).toBe(true)
      if (!parsed.success) return

      let values: PostWriteInput = parsed.data
      if (testCase.profile) {
        values = applyProfilePrefill(values, profileRow(testCase.profile))
      }

      expect({
        ...values,
        current_stage: STAGES[0],
        stage_status: { [STAGES[0]]: STATUS_RUNNING },
      }).toEqual(testCase.post)
      expect(testCase.enqueued_jobs).toEqual(["run_pipeline_stage"])
    })
  }
})

// --- The handler ------------------------------------------------------------

describe("POST /api/posts", () => {
  it("rejects an unauthenticated request the way get_current_user did", async () => {
    const response = await create({ slug: `${PREFIX}nope`, topic: "T" })
    expect(response.status).toBe(401)
    await expect(response.json()).resolves.toEqual({ detail: "Not authenticated" })
  })

  it("answers a body that is not JSON with FastAPI's json_invalid 422", async () => {
    const response = await create("{not json", user.cookie)
    expect(response.status).toBe(422)
    await expect(response.json()).resolves.toEqual({
      detail: [{ type: "json_invalid", loc: ["body", 0], msg: "JSON decode error", input: {} }],
    })
  })

  it("answers a missing required field with pydantic's missing 422", async () => {
    const body = { topic: "No slug" }
    const response = await create(body, user.cookie)
    expect(response.status).toBe(422)
    await expect(response.json()).resolves.toEqual({
      detail: [{ type: "missing", loc: ["body", "slug"], msg: "Field required", input: body }],
    })
  })

  it("answers an unparseable word_count with pydantic's int_parsing 422", async () => {
    const response = await create(
      { slug: `${PREFIX}bad-int`, topic: "T", word_count: "abc" },
      user.cookie,
    )
    expect(response.status).toBe(422)
    await expect(response.json()).resolves.toEqual({
      detail: [
        {
          type: "int_parsing",
          loc: ["body", "word_count"],
          msg: "Input should be a valid integer, unable to parse string as an integer",
          input: "abc",
        },
      ],
    })
  })

  it("separates pydantic's two uuid failures for profile_id", async () => {
    const parsing = await create(
      { slug: `${PREFIX}bad-uuid`, topic: "T", profile_id: "not-a-uuid" },
      user.cookie,
    )
    expect(parsing.status).toBe(422)
    await expect(parsing.json()).resolves.toEqual({
      detail: [
        {
          type: "uuid_parsing",
          loc: ["body", "profile_id"],
          msg: "Input should be a valid UUID",
          input: "not-a-uuid",
        },
      ],
    })

    const typed = await create(
      { slug: `${PREFIX}bad-uuid-type`, topic: "T", profile_id: 5 },
      user.cookie,
    )
    expect(typed.status).toBe(422)
    await expect(typed.json()).resolves.toEqual({
      detail: [
        {
          type: "uuid_type",
          loc: ["body", "profile_id"],
          msg: "UUID input should be a string, bytes or UUID object",
          input: 5,
        },
      ],
    })
  })

  it("coerces an integral string to an int the way pydantic's lax mode does", async () => {
    const profile = await insertProfile(user.userId)
    const response = await create(
      {
        slug: `${PREFIX}lax`,
        topic: "T",
        profile_id: profile.id,
        word_count: " 2500 ",
        stage_settings: GATED_STAGE_SETTINGS,
      },
      user.cookie,
    )
    expect(response.status).toBe(201)
    await expect(response.json()).resolves.toMatchObject({ word_count: 2500 })
  })

  it("writes the pydantic defaults, not the column defaults, and stamps the first stage", async () => {
    // The only body here with no review gate, so the run is not really started.
    start.mode = "skip"
    const response = await create({ slug: `${PREFIX}minimal`, topic: "Minimal topic" }, user.cookie)
    expect(response.status).toBe(201)

    const body = await response.json()
    expect(body).toMatchObject({
      slug: `${PREFIX}minimal`,
      topic: "Minimal topic",
      profile_id: null,
      word_count: 2000,
      tone: "Conversational and friendly",
      // The column default is "both" and the pydantic default is "markdown".
      output_format: "markdown",
      related_keywords: [],
      competitor_urls: [],
      image_brand_colors: [],
      image_exclude: [],
      // The column default is five "review" stages; pydantic's is six "auto" ones.
      stage_settings: {
        research: "auto",
        outline: "auto",
        write: "auto",
        edit: "auto",
        images: "auto",
        ready: "auto",
      },
      current_stage: "research",
      stage_status: { research: "running" },
    })
  })

  it("fills unset fields from the caller's profile and persists them", async () => {
    const profile = await insertProfile(user.userId, {
      niche: "Roofing",
      targetAudience: "Homeowners",
      tone: "Profile tone",
      wordCount: 3300,
      outputFormat: "html",
      relatedKeywords: ["profile keyword"],
      wpDefaultCategoryId: 77,
      wpDefaultAuthorId: 88,
    })

    const response = await create(
      { slug: `${PREFIX}prefilled`, topic: "Prefilled", profile_id: profile.id },
      user.cookie,
    )
    expect(response.status).toBe(201)
    const body = await response.json()
    expect(body).toMatchObject({
      niche: "Roofing",
      target_audience: "Homeowners",
      tone: "Profile tone",
      word_count: 3300,
      output_format: "html",
      website_url: SITE,
      related_keywords: ["profile keyword"],
      stage_settings: GATED_STAGE_SETTINGS,
      wp_category_id: 77,
      wp_author_id: 88,
    })

    const [row] = await db.select().from(posts).where(eq(posts.id, body.id)).limit(1)
    expect(row).toMatchObject({
      niche: "Roofing",
      wordCount: 3300,
      outputFormat: "html",
      relatedKeywords: ["profile keyword"],
      stageSettings: GATED_STAGE_SETTINGS,
      wpCategoryId: 77,
      wpAuthorId: 88,
    })
  })

  it("lets a body that differs from the schema default beat the profile", async () => {
    const profile = await insertProfile(user.userId, { tone: "Profile tone", wordCount: 3300 })

    const response = await create(
      {
        slug: `${PREFIX}explicit`,
        topic: "Explicit",
        profile_id: profile.id,
        tone: "Body tone",
        word_count: 4400,
      },
      user.cookie,
    )
    expect(response.status).toBe(201)
    await expect(response.json()).resolves.toMatchObject({
      tone: "Body tone",
      word_count: 4400,
    })
  })

  it("does not read another user's profile, and writes no post when it refuses", async () => {
    const theirs = await insertProfile(other.userId, { niche: "Theirs" })

    const response = await create(
      { slug: `${PREFIX}cross-tenant`, topic: "T", profile_id: theirs.id },
      user.cookie,
    )
    expect(response.status).toBe(404)
    await expect(response.json()).resolves.toEqual({ detail: "Profile not found" })

    const rows = await db.select().from(posts).where(like(posts.slug, `${PREFIX}%`))
    expect(rows).toEqual([])
  })

  it("starts the pipeline on the Redis Streams bus", async () => {
    const profile = await insertProfile(user.userId)
    const response = await create(
      { slug: `${PREFIX}enqueued`, topic: "Enqueued", profile_id: profile.id },
      user.cookie,
    )
    expect(response.status).toBe(201)
    const { id } = await response.json()

    const event = await waitForStart(id)
    expect(event.type).toBe("workflow.start")
    expect(event.data?.workflowId).toBe("pipeline")
  })

  it("still returns the 201 when the run cannot be started", async () => {
    start.mode = "throw"
    const warn = vi.spyOn(logger, "warn").mockImplementation(() => {})
    const profile = await insertProfile(user.userId)

    const response = await create(
      { slug: `${PREFIX}queue-down`, topic: "Queue down", profile_id: profile.id },
      user.cookie,
    )
    // Python let this escape as a 500, reporting a create that in fact
    // succeeded. The row is written either way, so the 201 is the honest answer.
    expect(response.status).toBe(201)
    const { id } = await response.json()

    const [row] = await db.select().from(posts).where(eq(posts.id, id)).limit(1)
    expect(row.slug).toBe(`${PREFIX}queue-down`)
    expect(warn).toHaveBeenCalledWith(
      "Post created but the pipeline could not be started",
      expect.objectContaining({ postId: id, error: "redis is down" }),
    )
    warn.mockRestore()
  })

  it("returns a post the ported read endpoint then serves identically", async () => {
    const profile = await insertProfile(user.userId, { niche: "Roofing" })
    const created = await create(
      { slug: `${PREFIX}round-trip`, topic: "Round trip", profile_id: profile.id },
      user.cookie,
    )
    expect(created.status).toBe(201)
    const body = await created.json()

    const read = await getPost(apiRequest(`${URL_BASE}/${body.id}`, { cookie: user.cookie }), {
      params: Promise.resolve({ id: body.id }),
    })
    expect(read.status).toBe(200)
    await expect(read.json()).resolves.toEqual(body)
  })
})
