/**
 * Parity tests for `optimizeImage` against Pillow's `optimize_image`.
 *
 * The corpus in `data/optimize-parity` is generated by
 * `api/scripts/export_optimize_parity.py`, which runs the Python implementation
 * over deterministic PNG inputs and commits both the inputs and Pillow's WebP
 * output. It exists because the golden fixtures cannot serve as the oracle
 * here: every Gemini call recorded in them returned a 429, so no real generated
 * image was ever optimized.
 *
 * What the corpus proved, and what these tests therefore pin:
 *
 * 1. When no resize happens, Pillow and sharp produce **byte-identical** WebP.
 *    Both link libwebp 1.6.0 and both drive it with quality 82, method/effort 4
 *    and alpha quality 100, so the encoder half of this function is not an
 *    approximation, it is an equality. Four cases assert that.
 * 2. When a resize happens the resamplers differ (Pillow's own Lanczos
 *    convolution vs libvips' reduce), so only the dimensions are exact. The
 *    decoded pixels stay within the tolerances measured below.
 */

import { readFileSync } from "node:fs";
import path from "node:path";
import sharp from "sharp";
import { describe, expect, it } from "vitest";
import { OPTIMIZE_QUALITY, optimizeImage } from "./optimize";

const DATA_DIR = path.resolve(__dirname, "data/optimize-parity");

interface ParityCase {
  name: string;
  why: string;
  max_width: number;
  input: string;
  input_mode: string;
  input_width: number;
  input_height: number;
  expected: string;
  expected_ext: string;
  expected_width: number;
  expected_height: number;
  expected_bytes: number;
}

const CASES: ParityCase[] = JSON.parse(
  readFileSync(path.join(DATA_DIR, "index.json"), "utf8"),
);

/**
 * Tolerances for the cases that are resized, keyed by case name. The default
 * covers every opaque RGB case; the two overrides are documented divergences,
 * not slack for its own sake.
 */
const DEFAULT_TOLERANCE = { mae: 1.7, maxDiff: 48 };
const TOLERANCE: Record<string, { mae: number; maxDiff: number; why: string }> =
  {
    // Pillow resizes premultiplied (it converts RGBA to RGBa first), and so
    // does libvips, but unpremultiplying a nearly transparent pixel amplifies
    // any difference by up to 255x. Above alpha 8 the measured max difference
    // drops back to 63.
    "alpha-1600x900-w1200": {
      mae: 5,
      maxDiff: 255,
      why: "unpremultiply amplifies differences where alpha is near zero",
    },
    // Pillow's Image.resize overrides the caller's filter with NEAREST for
    // modes "1" and "P", so Python's palette output is nearest-neighbour while
    // sharp's is lanczos3. Sharp's is the better image; this is an accepted
    // divergence, recorded rather than reproduced.
    "palette-1600x900-w1200": {
      mae: 5,
      maxDiff: 192,
      why: "Pillow forces NEAREST for palette images, ignoring LANCZOS",
    },
  };

/** Encoded size may drift with the resampler; measured range was 0.91x-1.03x. */
const SIZE_RATIO = { min: 0.85, max: 1.15 };

async function toRgba(buffer: Buffer) {
  const { data, info } = await sharp(buffer)
    .ensureAlpha()
    .raw()
    .toBuffer({ resolveWithObject: true });
  return { data, width: info.width, height: info.height };
}

function compare(a: Buffer | Uint8Array, b: Buffer | Uint8Array) {
  let sum = 0;
  let maxDiff = 0;
  for (let i = 0; i < b.length; i++) {
    const diff = Math.abs(a[i] - b[i]);
    sum += diff;
    if (diff > maxDiff) maxDiff = diff;
  }
  return { mae: sum / b.length, maxDiff };
}

function readCase(parityCase: ParityCase) {
  return {
    input: readFileSync(path.join(DATA_DIR, parityCase.input)),
    expected: readFileSync(path.join(DATA_DIR, parityCase.expected)),
  };
}

describe("optimizeImage parity with Pillow", () => {
  it("has a corpus covering both the resized and the untouched path", () => {
    expect(CASES.length).toBe(14);
    expect(CASES.filter((c) => c.input_width > c.max_width).length).toBe(10);
    expect(CASES.filter((c) => c.input_width <= c.max_width).length).toBe(4);
    expect(new Set(CASES.map((c) => c.input_mode))).toEqual(
      new Set(["RGB", "RGBA", "L", "P"]),
    );
  });

  for (const parityCase of CASES) {
    describe(`${parityCase.name} (${parityCase.why})`, () => {
      it("returns the same dimensions Pillow produced", async () => {
        const { input } = readCase(parityCase);
        const { bytes, ext } = await optimizeImage(input, parityCase.max_width);
        const meta = await sharp(bytes).metadata();

        expect(ext).toBe(parityCase.expected_ext);
        expect(meta.format).toBe("webp");
        expect(meta.width).toBe(parityCase.expected_width);
        expect(meta.height).toBe(parityCase.expected_height);
      });

      it("encodes within Pillow's size envelope", async () => {
        const { input } = readCase(parityCase);
        const { bytes } = await optimizeImage(input, parityCase.max_width);
        const ratio = bytes.length / parityCase.expected_bytes;

        expect(ratio).toBeGreaterThanOrEqual(SIZE_RATIO.min);
        expect(ratio).toBeLessThanOrEqual(SIZE_RATIO.max);
      });

      if (parityCase.input_width <= parityCase.max_width) {
        it("is byte-identical to Pillow, since no resize happens", async () => {
          const { input, expected } = readCase(parityCase);
          const { bytes } = await optimizeImage(input, parityCase.max_width);

          expect(bytes.length).toBe(parityCase.expected_bytes);
          expect(Buffer.compare(bytes, expected)).toBe(0);
        });
      } else {
        const tolerance = TOLERANCE[parityCase.name] ?? DEFAULT_TOLERANCE;
        it("decodes to pixels within tolerance of Pillow's", async () => {
          const { input, expected } = readCase(parityCase);
          const { bytes } = await optimizeImage(input, parityCase.max_width);
          const mine = await toRgba(bytes);
          const theirs = await toRgba(expected);

          expect([mine.width, mine.height]).toEqual([
            theirs.width,
            theirs.height,
          ]);
          const { mae, maxDiff } = compare(mine.data, theirs.data);
          expect(mae).toBeLessThanOrEqual(tolerance.mae);
          expect(maxDiff).toBeLessThanOrEqual(tolerance.maxDiff);
        });
      }
    });
  }
});

describe("optimizeImage resize decisions", () => {
  const wide = CASES.find((c) => c.name === "odd-1600x901-w1200")!;
  const exact = CASES.find((c) => c.name === "exact-1200x800-w1200")!;

  it("truncates the scaled height rather than rounding it", async () => {
    // 901 * (1200 / 1600) is 675.75; Python's int() gives 675, round() 676.
    const { input } = readCase(wide);
    const { bytes } = await optimizeImage(input, 1200);

    expect((await sharp(bytes).metadata()).height).toBe(675);
  });

  it("leaves an image whose width equals max_width untouched", async () => {
    const { input } = readCase(exact);
    const { bytes } = await optimizeImage(input, 1200);
    const meta = await sharp(bytes).metadata();

    expect([meta.width, meta.height]).toEqual([1200, 800]);
  });

  it("never upscales a narrower image", async () => {
    const small = CASES.find((c) => c.name === "small-800x600-w1200")!;
    const { input } = readCase(small);
    const { bytes } = await optimizeImage(input, 1200);
    const meta = await sharp(bytes).metadata();

    expect([meta.width, meta.height]).toEqual([800, 600]);
  });

  it("uses the featured width when the stage passes 1920", async () => {
    // The stage picks 1920 for featured images and 1200 for the rest.
    const featured = CASES.find((c) => c.name === "smooth-2400x1350-w1920")!;
    const { input } = readCase(featured);
    const { bytes } = await optimizeImage(input, 1920);
    const meta = await sharp(bytes).metadata();

    expect([meta.width, meta.height]).toEqual([1920, 1080]);
  });

  it("defaults to Pillow's max_width of 1200", async () => {
    // Driven from a 2400px input, so a default of 1920 would show up here.
    const oversized = CASES.find((c) => c.name === "smooth-2400x1350-w1200")!;
    const { input } = readCase(oversized);
    const { bytes } = await optimizeImage(input);
    const meta = await sharp(bytes).metadata();

    expect([meta.width, meta.height]).toEqual([1200, 675]);
  });

  it("defaults to Pillow's quality of 82", async () => {
    const { input, expected } = readCase(exact);
    const { bytes } = await optimizeImage(input);

    // The corpus entry for this case was produced with Pillow's defaults, and
    // the no-resize path is byte-identical, so any other quality shows up as a
    // byte difference.
    expect(OPTIMIZE_QUALITY).toBe(82);
    expect(Buffer.compare(bytes, expected)).toBe(0);
  });
});

describe("optimizeImage failure path", () => {
  it("rejects input that is not a decodable image", async () => {
    const error = await optimizeImage(Buffer.from("not an image")).catch(
      (e: Error) => e,
    );

    expect(error).toBeInstanceOf(Error);
    expect((error as Error).message).toMatch(/unsupported image format/i);
  });
});

describe("optimizeImage resampling kernel", () => {
  /**
   * Pillow's LANCZOS has no exact libvips equivalent, so the kernel was chosen
   * by measurement rather than by name matching. Summed over every resized case
   * in the corpus, lanczos3 is closer to Pillow's output than any other kernel
   * sharp offers. Driving the implementation's own number through
   * `optimizeImage` means switching the kernel makes this fail instead of
   * quietly costing image fidelity.
   */
  const RESIZED = CASES.filter((c) => c.input_width > c.max_width);
  const ALTERNATIVES = ["cubic", "mitchell", "lanczos2"] as const;

  async function distanceFromPillow(bytes: Buffer, parityCase: ParityCase) {
    const mine = await toRgba(bytes);
    const theirs = await toRgba(
      readFileSync(path.join(DATA_DIR, parityCase.expected)),
    );
    return compare(mine.data, theirs.data).mae;
  }

  it("is closer to Pillow's LANCZOS than any other sharp kernel", async () => {
    let implementation = 0;
    const alternatives: Record<string, number> = { cubic: 0, mitchell: 0, lanczos2: 0 };

    for (const parityCase of RESIZED) {
      const input = readFileSync(path.join(DATA_DIR, parityCase.input));
      const { bytes } = await optimizeImage(input, parityCase.max_width);
      implementation += await distanceFromPillow(bytes, parityCase);

      for (const kernel of ALTERNATIVES) {
        const image = sharp(input);
        const { width, height } = await image.metadata();
        const other = await image
          .resize({
            width: parityCase.max_width,
            height: Math.trunc(height! * (parityCase.max_width / width!)),
            fit: "fill",
            kernel,
          })
          .webp({
            quality: OPTIMIZE_QUALITY,
            effort: 4,
            alphaQuality: 100,
            lossless: false,
            nearLossless: false,
            smartSubsample: false,
          })
          .toBuffer();
        alternatives[kernel] += await distanceFromPillow(other, parityCase);
      }
    }

    for (const kernel of ALTERNATIVES) {
      expect(
        implementation,
        `expected the shipped kernel to beat ${kernel}`,
      ).toBeLessThan(alternatives[kernel]);
    }
  }, 60_000);
});
