import type { GeneratedFile, FrontmatterMapping, JenaConfig } from "../types.js";
import { generateWebhookHandler } from "../adapters/delivery/webhook.js";

interface ConnectOptions {
  rootDir: string;
  contentDir: string;
  frontmatterMapping: FrontmatterMapping;
  imageStorage: "local" | "jena-cdn";
  siteName?: string;
  siteUrl?: string;
}

interface ConnectResult {
  files: GeneratedFile[];
  envVars: Record<string, string>;
}

export async function connectToExistingBlog(
  options: ConnectOptions,
): Promise<ConnectResult> {
  const {
    contentDir,
    frontmatterMapping,
    imageStorage,
    siteName = "",
    siteUrl = "",
  } = options;
  const files: GeneratedFile[] = [];

  // Generate webhook handler
  const webhookHandler = generateWebhookHandler({
    typescript: true,
    contentDir,
    imageStorage,
    localImageDir: "public/blog/images",
    localImagePublicPath: "/blog/images",
  });
  files.push({ path: "app/api/jena-webhook/route.ts", content: webhookHandler });

  // Generate config file
  const config: Partial<JenaConfig> = {
    blog: {
      contentDir,
      postsPerPage: 10,
      rss: false,
      categories: false,
      siteName,
      siteDescription: "",
      siteUrl,
    },
    jena: {
      apiKey: undefined,
      webhookSecret: undefined,
    },
    frontmatter: frontmatterMapping,
    images: { storage: imageStorage },
  };

  const configContent = generateConnectConfigFile(config);
  files.push({ path: "jena.config.ts", content: configContent });

  return { files, envVars: {} };
}

function generateConnectConfigFile(config: Partial<JenaConfig>): string {
  const configObj = {
    blog: config.blog,
    jena: {
      apiKey: "process.env.JENA_API_KEY",
      webhookSecret: "process.env.JENA_WEBHOOK_SECRET",
    },
    frontmatter: config.frontmatter ?? {},
    images: config.images ?? { storage: "jena-cdn" },
  };

  let json = JSON.stringify(configObj, null, 2);
  json = json.replace(/"process\.env\.(\w+)"/g, "process.env.$1");

  return `/**
 * Jena AI blog integration config.
 * Generated by create-mdx-blog (connect mode).
 */

interface JenaConfig {
  blog: {
    contentDir: string;
    postsPerPage: number;
    rss: boolean;
    categories: boolean;
    siteName: string;
    siteDescription: string;
    siteUrl: string;
  };
  jena?: {
    apiKey: string | undefined;
    webhookSecret: string | undefined;
  };
  frontmatter: Record<
    string,
    string | { key: string; transform?: string; default?: string }
  >;
  images: {
    storage: "local" | "jena-cdn";
    localDir?: string;
    publicPath?: string;
  };
}

const config: JenaConfig = ${json};

export default config;
`;
}
