/**
 * `fromIsoFormat()` and `toPythonUtcIsoFormat()`, the two halves of the
 * `datetime.fromisoformat(x).isoformat()` round trip `search_logs()` in
 * `api/src/api/analytics.py` performs on `since` and `until`.
 *
 * The oracle is `data/from-isoformat-parity.json`, generated by running each
 * case through the CPython that serves the FastAPI router. Both `since` and
 * `until` are compared as *text* against `log_entry->>'ts'`, so the normalised
 * string is the whole behaviour: a `Z` suffix that survives into the query
 * sorts above a stored `+00:00` and silently drops entries.
 */
import { describe, expect, it } from "vitest"

import { fromIsoFormat, toPythonUtcIsoFormat } from "./from-isoformat"

import oracle from "./data/from-isoformat-parity.json"

describe("fromIsoFormat", () => {
  it("reads the oracle table CPython generated", () => {
    expect(oracle.python.startsWith("3.")).toBe(true)
    expect(oracle.cases.length).toBeGreaterThanOrEqual(128)
    expect(oracle.cases.some((row) => row.out === null)).toBe(true)
  })

  for (const row of oracle.cases) {
    const label = row.out === null ? "rejects" : `normalises to ${row.out}`
    it(`${label}: ${JSON.stringify(row.in)}`, () => {
      expect(fromIsoFormat(row.in)).toBe(row.out)
    })
  }

  it("normalises the exact string the logs tab sends", () => {
    // `new Date(...).toISOString()` in `monitor/_components/logs-tab.tsx`.
    const sent = new Date(Date.UTC(2026, 7, 23, 12, 34, 56, 789)).toISOString()
    expect(sent).toBe("2026-08-23T12:34:56.789Z")
    expect(fromIsoFormat(sent)).toBe("2026-08-23T12:34:56.789000+00:00")
  })

  it("keeps a normalised value orderable against a stored ts", () => {
    // `log_entry->>'ts'` is `datetime.now(UTC).isoformat()`, so a normalised
    // lower bound has to compare byte-wise against that shape.
    const stored = "2026-08-23T12:34:56.789012+00:00"
    expect(fromIsoFormat("2026-08-23T12:34:56.789Z")! <= stored).toBe(true)
    expect(fromIsoFormat("2026-08-23T12:34:57Z")! <= stored).toBe(false)
  })
})

describe("toPythonUtcIsoFormat", () => {
  it("renders an aware UTC datetime the way Python does", () => {
    expect(toPythonUtcIsoFormat(new Date(Date.UTC(2026, 4, 25, 1, 2, 3, 40)))).toBe(
      "2026-05-25T01:02:03.040000+00:00",
    )
  })

  it("omits the fraction when the millisecond is zero, as Python omits microsecond 0", () => {
    expect(toPythonUtcIsoFormat(new Date(Date.UTC(2026, 4, 25, 1, 2, 3)))).toBe(
      "2026-05-25T01:02:03+00:00",
    )
  })

  it("round-trips through fromIsoFormat unchanged", () => {
    const rendered = toPythonUtcIsoFormat(new Date(Date.UTC(2026, 4, 25, 1, 2, 3, 456)))
    expect(fromIsoFormat(rendered)).toBe(rendered)
  })
})
